import type { DecisionTreeNode } from "../decision-tree.types";
import { leafNode } from "./shared";

// ═══════════════════════════════════════════════
// ARTS / HUMANITIES STREAM
// ═══════════════════════════════════════════════

export const ARTS_STREAM: DecisionTreeNode = {
  id: "arts",
  name: "Arts & Humanities Stream",
  shortDescription: "For creative minds, critical thinkers, and changemakers — the most versatile stream",
  detailedDescription: "Arts/Humanities is the broadest stream after Class 10, covering literature, history, political science, psychology, sociology, fine arts, journalism, and more. It is NOT the 'last option' — it's the stream that produces civil servants, lawyers, journalists, psychologists, diplomats, authors, filmmakers, and policymakers. With new-age careers like UX design, content strategy, and social media management, arts graduates are in demand across industries.",
  iconName: "Palette",
  color: "from-purple-600 to-purple-400",
  educationPath: ["11th-12th Arts/Humanities", "Bachelor's degree (BA)", "MA/MSW/LLB/MBA (optional)", "UPSC/professional certs"],
  entranceExams: ["CUET-UG", "CLAT", "NIFT", "NID DAT", "UCEED", "IPU CET (Mass Comm)", "TISS NET"],
  topColleges: [
    { name: "St. Stephen's Delhi", location: "Delhi", fees: "₹50K - ₹1L/yr" },
    { name: "LSR Delhi", location: "Delhi", fees: "₹30K - ₹70K/yr" },
    { name: "TISS Mumbai", location: "Mumbai", fees: "₹2L - ₹4L/yr" },
    { name: "Ashoka University", location: "Sonipat", fees: "₹4L - ₹8L/yr" },
  ],
  salaryRanges: { entry: "₹3L - ₹8L", mid: "₹8L - ₹20L", senior: "₹20L - ₹1Cr+" },
  growthOutlook: "High",
  skillsRequired: ["Critical Thinking", "Communication", "Writing", "Research", "Empathy", "Creativity", "Analysis"],
  specializations: ["UPSC/Civil Services", "Law", "Psychology", "Journalism", "Design", "Social Work", "Teaching"],
  certifications: ["NET/JRF", "SET", "CTET", "PG Diploma programs"],
  topRecruiters: ["Government", "NGOs", "UN Agencies", "Media Houses", "Design Studios", "Law Firms", "Think Tanks"],
  workEnvironment: "Varies enormously — courtroom to newsroom, design studio to government office, classroom to corporate office.",
  governmentJobs: ["UPSC (IAS/IPS/IFS)", "State PSCs", "SSC CGL", "Banking", "Teaching (NET/SET)", "Railways"],
  privateJobs: ["Law Firms", "Media & Publishing", "Advertising", "Design Firms", "NGOs", "Corporates (HR/Comms)"],
  researchOpportunities: ["PhD in Humanities", "Social Science Research", "JRF/NET Research Fellowships", "Policy Research"],
  entrepreneurshipPotential: "Start a law firm, design studio, NGO, content agency, publishing house, or coaching institute",
  futureScope: ["Content economy booming", "UX/Design roles in tech", "Social media management careers", "Legal tech & policy consulting growth"],
  pros: ["Most versatile stream — open all career paths", "Builds critical thinking and communication", "Gateway to UPSC/Civil Services", "New-age careers (design, content, UX)"],
  cons: ["No direct STEM career path", "Perceived lower prestige (wrongly)", "Some careers need additional qualifications", "Top college matters for some roles"],
  category: "Arts",
  timeToComplete: "3-6 years",
  children: [
    // UPSC / Civil Services
    leafNode("arts-upsc", "UPSC / Civil Services", "Serve the nation as IAS, IPS, IFS officer",
      "The Indian Civil Services — one of India's most prestigious career paths. Selected through the famously challenging UPSC exam (CSE), officers manage districts (IAS), police forces (IPS), foreign relations (IFS), and central services. The exam has 3 stages: Prelims (MCQ), Mains (9 descriptive papers), and Interview. Liberal arts education is excellent preparation for CS.",
      "from-amber-500 to-orange-400",
      { iconName: "Shield", educationPath: ["12th (any stream)", "Bachelor's (any stream)", "UPSC CSE Preparation", "Prelims → Mains → Interview"],
        entranceExams: ["UPSC CSE"], salaryRanges: { entry: "₹10L - ₹18L", mid: "₹20L - ₹35L", senior: "₹35L - ₹50L+" }, growthOutlook: "Stable", topColleges: [{ name: "LBSNAA Mussoorie", location: "Mussoorie", fees: "N/A (govt)" }],
        skillsRequired: ["Analytical Ability", "Essay Writing", "Decision Making", "Leadership", "Indian Polity & History", "Current Affairs"],
        specializations: ["IAS", "IPS", "IFS", "IRS", "IAAS", "IPoS", "Central Services"],
        certifications: ["Foundation Course (LBSNAA)", "Mid-Career Training Programs"],
        topRecruiters: ["Government of India", "State Governments", "PSUs (on deputation)", "International Organizations (UN/World Bank on deputation)"],
        workEnvironment: "Government offices with significant field work. IAS/IPS involves district postings, public interaction, crisis management. High authority and responsibility.",
        governmentJobs: ["IAS", "IPS", "IFS", "IRS", "IAAS", "IPoS", "IIS", "IDES"], privateJobs: ["Consulting (post-retirement)", "Corporate Board positions"],
        entrepreneurshipPotential: "Post-retirement, many ex-IAS officers start consultancies, NGOs, or join corporate boards",
        futureScope: ["Digital governance creating new roles", "Policy-making complexity increasing", "International postings expanding", "Specialized domains (cyber, climate)"],
        pros: ["Unmatched prestige and authority", "Job security and pension", "Impact millions of lives", "Diverse career (different postings, challenges)"], cons: ["Extremely competitive (0.1% selection)", "Years of preparation (2-4yr avg)", "Postings in difficult areas", "Bureaucratic constraints"],
        category: "Arts", timeToComplete: "5 - 7 years" }
    ),
    // Law
    leafNode("arts-law", "Law (LLB / Integrated)", "Uphold justice — argue, advise, advocate",
      "Law is one of India's most lucrative and respected professions. Path: 5-year integrated BA LLB from NLU (via CLAT) after 12th, or 3-year LLB after graduation. Lawyers work in litigation, corporate law, IP law, criminal law, and more. Corporate law at top firms starts at ₹12-18L, with partners earning ₹1Cr+. Judiciary is another prestigious path.",
      "from-indigo-600 to-blue-500",
      { iconName: "Scale", educationPath: ["12th (any stream)", "5yr BA LLB (CLAT)", "Bar Council Enrollment", "LLM (optional specialization)"],
        entranceExams: ["CLAT", "AILET", "LSAT-India", "SLAT", "MH CET Law"], salaryRanges: { entry: "₹6L - ₹18L", mid: "₹16L - ₹40L", senior: "₹40L - ₹2Cr+" }, growthOutlook: "Very High", topColleges: [{ name: "NLSIU Bangalore", location: "Bangalore", fees: "₹2L - ₹4L/yr" }, { name: "NALSAR Hyderabad", location: "Hyderabad", fees: "₹2L - ₹4L/yr" }, { name: "NLU Delhi", location: "Delhi", fees: "₹1L - ₹3L/yr" }],
        skillsRequired: ["Legal Reasoning", "Argumentation", "Drafting", "Research", "Negotiation", "Attention to Detail"],
        specializations: ["Corporate Law", "Criminal Law", "Constitutional Law", "IP Law", "Environmental Law", "Cyber Law", "International Law", "Tax Law"],
        certifications: ["Bar Council Enrollment", "Company Secretary (combo)", "LLM", "Mediation Certification"],
        topRecruiters: ["Amarchand Mangaldas", "AZB & Partners", "Trilegal", "Khaitan & Co", "Luthra & Luthra", "Corporate Legal Depts", "Litigation"],
        workEnvironment: "Courtrooms, law firm offices, corporate legal departments. Litigation involves court appearances; corporate law is desk-based. Both can be high-pressure during case deadlines.",
        governmentJobs: ["Judicial Services (Judge)", "Public Prosecutor", "Government Legal Advisor", "Law Commission", "UPSC Law Officer"], privateJobs: ["Law Firms", "Corporate (In-House Counsel)", "LPOs", "Arbitration"],
        entrepreneurshipPotential: "Start independent law practice or boutique law firm — most Indian lawyers are self-employed",
        futureScope: ["Corporate India growing → legal demand", "IP, tech, data privacy law booming", "International arbitration hub (Singapore/Dubai)", "Legal tech (AI-assisted research)"],
        pros: ["Prestigious profession", "High earning (corporate tier-1)", "Can practice independently", "Diverse specializations"], cons: ["Expensive education (NLUs ~₹15-20L)", "Litigation takes years to establish", "Long hours in corporate law", "CLAT is highly competitive"],
        category: "Arts", timeToComplete: "5 - 8 years" }
    ),
    // Psychology
    leafNode("arts-psychology", "Psychology & Mental Health", "Understand minds — heal and empower people",
      "Psychology is a rapidly growing field in India as mental health awareness increases. Path: BA/B.Sc Psychology → MA Psychology (specialization) → M.Phil/Psy.D for clinical practice. Career paths include clinical psychology, counseling, organizational psychology (HR/corporate), forensic psychology, and sports psychology. RCI registration required for clinical practice.",
      "from-pink-400 to-rose-500",
      { iconName: "Brain", educationPath: ["12th (any stream, Psych preferred)", "BA/B.Sc Psychology (3yr)", "MA/M.Sc Psychology (2yr)", "M.Phil Clinical Psych / Psy.D (for clinical)"],
        entranceExams: ["CUET-UG", "CUET-PG", "TISS NET", "NIMHANS Entrance"], salaryRanges: { entry: "₹4L - ₹8L", mid: "₹8L - ₹20L", senior: "₹20L - ₹50L+" }, growthOutlook: "Very High", topColleges: [{ name: "LSR Delhi", location: "Delhi", fees: "₹30K - ₹70K/yr" }, { name: "TISS Mumbai", location: "Mumbai", fees: "₹2L - ₹4L/yr" }, { name: "NIMHANS Bangalore", location: "Bangalore", fees: "₹20K - ₹50K/yr" }],
        skillsRequired: ["Empathy", "Active Listening", "Research Methods", "Assessment & Diagnosis", "Counseling Skills", "Patience"],
        specializations: ["Clinical Psychology", "Counseling Psychology", "Organizational Psychology", "Forensic Psychology", "Child Psychology", "Sports Psychology", "Neuropsychology"],
        certifications: ["RCI Registration (Clinical Psychologist)", "CBT Practitioner", "Play Therapy Certification", "Psychometric Assessment"],
        topRecruiters: ["Hospitals & Clinics", "Schools/Universities", "Corporate (EAP/HR)", "NGOs", "Private Practice"],
        workEnvironment: "Clinic/hospital for clinical, corporate office for organizational, school/college for counseling. Private practice offers flexibility.",
        governmentJobs: ["Government Hospitals", "AIIMS", "NIMHANS", "Defence (Military Psychologist)", "Prison Psychology", "Rehabilitation Centres"], privateJobs: ["Private Hospitals", "Corporates (EAP)", "Schools/Universities", "Private Practice"],
        entrepreneurshipPotential: "Start private psychology practice, mental health startup, or counseling center — growing demand",
        futureScope: ["Mental health awareness exploding post-COVID", "Corporate wellness programs expanding", "Teletherapy/online counseling growth", "School counselor mandate (CBSE)"],
        pros: ["Growing demand (mental health focus)", "Private practice independence", "Rewarding — help people directly", "Multiple career environments"], cons: ["Clinical needs M.Phil/RCI (5-7yr path)", "Emotional burnout risk", "Starting private practice takes time", "Societal stigma slowly changing"],
        category: "Arts", timeToComplete: "5 - 8 years (for clinical)" }
    ),
    // Journalism & Mass Communication
    leafNode("arts-journalism", "Journalism & Mass Communication", "Tell stories that shape the world",
      "Journalism and mass communication covers news reporting, TV/radio broadcasting, digital media, PR, advertising, filmmaking, and content creation. With digital media booming, opportunities have exploded. Path: BJMC (3yr degree) or BA + PG Diploma. Careers span traditional media (newspapers, TV), digital media (YouTube, news websites), PR agencies, and corporate communications.",
      "from-red-400 to-orange-400",
      { iconName: "Newspaper", educationPath: ["12th (any stream)", "BJMC / BA Journalism (3yr)", "MA/MJMC (2yr, optional)", "Internships + Portfolio"],
        entranceExams: ["IPU CET (BJMC)", "IIT (MJMC) Entrance", "IIMC Entrance", "TISS NET"], salaryRanges: { entry: "₹3L - ₹8L", mid: "₹8L - ₹25L", senior: "₹25L - ₹60L+" }, growthOutlook: "High", topColleges: [{ name: "IIMC Delhi", location: "Delhi", fees: "₹1L - ₹1.5L total" }, { name: "Symbiosis (SIMC)", location: "Pune", fees: "₹3L - ₹5L/yr" }, { name: "Lady Sri Ram (LSR)", location: "Delhi", fees: "₹30K - ₹70K/yr" }],
        skillsRequired: ["Writing & Editing", "Interviewing", "Research & Fact-Checking", "Video Production", "Social Media", "Digital Tools"],
        specializations: ["Print Journalism", "Broadcast/TV Journalism", "Digital Journalism", "Public Relations (PR)", "Advertising", "Photojournalism", "Documentary Filmmaking"],
        certifications: ["PG Diploma (IIMC)", "Digital Marketing Certification", "Video Editing certs", "Google News Initiative"],
        topRecruiters: ["Times Group", "NDTV", "BBC", "Network18", "The Hindu", "PR Agencies (Edelman, Weber Shandwick)", "Corporate Comms"],
        workEnvironment: "Newsroom for journalism, studio for broadcast, agency for PR/advertising. Fast-paced, deadline-driven. Digital journalists can work remotely.",
        governmentJobs: ["DD News", "AIR", "PIB", "State Information Depts", "Rajya Sabha TV"], privateJobs: ["Media Houses", "Digital News Startups", "PR Agencies", "Corporate Communications"],
        entrepreneurshipPotential: "Start YouTube/news channel, digital publication, PR agency, or freelance journalism business",
        futureScope: ["Digital media overtaking print", "Independent journalism (Substack/Patreon)", "Podcast/audio journalism boom", "AI + journalism emerging"],
        pros: ["Creative and impactful work", "Meet interesting people, travel", "Digital media democratized entry", "Specialize in areas of personal interest"], cons: ["Irregular/long hours (breaking news)", "Entry-level pay is low in journalism", "Press freedom concerns", "Job instability in traditional media"],
        category: "Arts", timeToComplete: "3 - 5 years" }
    ),
    // Design
    leafNode("arts-design", "Design (NID/NIFT/NIFT)", "Create products, spaces, and experiences people love",
      "Design careers span fashion, communication, product, UX/UI, interior, textile, and animation. India's premier design institutes — NID, NIFT, and private schools like Srishti — produce world-class designers. With every startup and MNC needing UX designers, this is a booming sector. 4-year B.Des after 12th via NID DAT / NIFT entrance / UCEED.",
      "from-fuchsia-400 to-pink-500",
      { iconName: "PenTool", educationPath: ["12th (any stream)", "B.Des (4yr) from NID/NIFT/IIT", "M.Des (2yr, optional for specialization)"],
        entranceExams: ["NID DAT", "NIFT Entrance", "UCEED (IITs)", "CEED (M.Des)"], salaryRanges: { entry: "₹5L - ₹12L", mid: "₹12L - ₹30L", senior: "₹30L - ₹70L+" }, growthOutlook: "Very High", topColleges: [{ name: "NID Ahmedabad", location: "Ahmedabad", fees: "₹2L - ₹4L/yr" }, { name: "NIFT Delhi", location: "Delhi", fees: "₹1.5L - ₹3L/yr" }, { name: "IDC IIT Bombay", location: "Mumbai", fees: "₹1L - ₹3L/yr" }],
        skillsRequired: ["Visual Thinking", "Creativity", "Adobe Creative Suite", "Figma/Sketch", "3D Modeling", "Typography", "User Research"],
        specializations: ["UX/UI Design", "Fashion Design", "Communication Design", "Product/Industrial Design", "Interior Design", "Animation/VFX", "Textile Design"],
        certifications: ["Google UX Design Certificate", "Adobe Certified Expert", "Interaction Design Foundation", "CG Spectrum (Animation)"],
        topRecruiters: ["Microsoft", "Google", "Amazon", "Flipkart", "Urban Ladder", "Design Studios (Pentagram)", "Fashion Houses", "Gaming Studios"],
        workEnvironment: "Design studio or in-house design team. Collaborative, creative. UX/UI remote-friendly. Fashion involves workshops and manufacturing visits.",
        governmentJobs: ["NID Faculty", "Government Design Projects", "NIFT Campus Placements (PSUs)"], privateJobs: ["Tech Companies (UX)", "Design Firms", "Fashion & Apparel", "Media & Entertainment"],
        entrepreneurshipPotential: "Start design studio, fashion label, freelance UX practice, or D2C product brand",
        futureScope: ["UX demand from every tech company and startup", "AI-assisted design tools creating new roles", "Indian fashion going global", "Metaverse/AR/VR design emerging"],
        pros: ["Creative fulfillment", "High demand (especially UX)", "Global opportunities", "Portfolio-based — less theory"], cons: ["Portfolio is everything — hard to start", "Freelance income can be variable", "NID/NIFT seats very limited", "Subjective — client/art director approval needed"],
        category: "Arts", timeToComplete: "4 - 6 years" }
    ),
    // English / Literature
    leafNode("arts-english", "English & Literature", "Master the language that connects the world",
      "BA/MA in English Literature opens careers in teaching, content writing, publishing, editing, journalism, civil services (English is a popular optional), advertising (copywriting), and corporate communications. Strong writing skills make lit graduates valuable in the content economy. NET/JRF qualifies for college/university teaching positions.",
      "from-teal-400 to-cyan-500",
      { iconName: "BookOpen", educationPath: ["12th Arts (English recommended)", "BA English Hons (3yr)", "MA English (2yr)", "NET/JRF for teaching, Ph.D for university"],
        entranceExams: ["CUET-UG", "CUET-PG", "NET/JRF (NTA)", "SET (State)"], salaryRanges: { entry: "₹3L - ₹7L", mid: "₹7L - ₹15L", senior: "₹15L - ₹30L" }, growthOutlook: "Moderate", topColleges: [{ name: "St. Stephen's Delhi", location: "Delhi", fees: "₹50K - ₹1L/yr" }, { name: "LSR Delhi", location: "Delhi", fees: "₹30K - ₹70K/yr" }, { name: "Ashoka University", location: "Sonipat", fees: "₹4L - ₹8L/yr" }],
        skillsRequired: ["Writing (Advanced)", "Literary Analysis", "Research", "Editing", "Communication", "Critical Theory"],
        specializations: ["American Literature", "Postcolonial Literature", "Linguistics", "Creative Writing", "Comparative Literature", "Cultural Studies"],
        certifications: ["NET/JRF", "CTET", "TEFL/CELTA", "Copywriting certs", "Editing certifications"],
        topRecruiters: ["Publishing Houses (Penguin, HarperCollins)", "Media & Journalism", "Universities & Colleges", "Content / EdTech (BYJU'S, Unacademy)", "Advertising Agencies"],
        workEnvironment: "Classroom (teaching), office (content/publishing), or freelance. Content industry allows remote work. Academia follows semester rhythms.",
        governmentJobs: ["College/University Professor (NET)", "School Teacher (TGT/PGT)", "UPSC (optional subject)", "SSC", "Banking"], privateJobs: ["Publishing", "Content Writing/Strategy", "EdTech", "Advertising (Copywriting)"],
        entrepreneurshipPotential: "Start content agency, publishing house, coaching institute, or freelance writing/editing business",
        futureScope: ["Content economy expansion", "EdTech content demand", "AI-assisted writing tools", "Global English teaching markets"],
        pros: ["Strong communication foundation", "Versatile across content industries", "Can freelance/publish independently", "Prepares well for UPSC"], cons: ["Direct career path less defined", "Teaching pays less initially", "Publishing industry is niche", "Content writing commoditized"],
        category: "Arts", timeToComplete: "3 - 7 years" }
    ),
    // History / Political Science
    leafNode("arts-polsci", "Political Science & International Relations", "Understand power — shape policy and diplomacy",
      "BA/MA in Political Science or International Relations opens careers in government, diplomacy, think tanks, journalism, NGOs, UN agencies, and academia. It's a popular UPSC subject and excellent preparation for civil services. IR specialization + MA from JNU/DU leads to international organizations and foreign policy roles.",
      "from-blue-500 to-sky-400",
      { iconName: "Landmark", educationPath: ["12th Arts", "BA Pol Science/IR (3yr)", "MA/MPA (JNU/DU, 2yr)", "UPSC / Think Tank / Ph.D"],
        entranceExams: ["CUET-UG", "CUET-PG (JNU/DU)", "UPSC CSE", "TISS NET"], salaryRanges: { entry: "₹4L - ₹10L", mid: "₹10L - ₹20L", senior: "₹20L - ₹50L+" }, growthOutlook: "High", topColleges: [{ name: "JNU Delhi", location: "Delhi", fees: "₹5K - ₹15K/yr" }, { name: "LSR Delhi", location: "Delhi", fees: "₹30K - ₹70K/yr" }, { name: "Ashoka University", location: "Sonipat", fees: "₹4L - ₹8L/yr" }],
        skillsRequired: ["Policy Analysis", "Research", "Diplomatic Writing", "Understanding of Political Systems", "Current Affairs", "Public Speaking"],
        specializations: ["International Relations", "Indian Politics", "Comparative Politics", "Public Policy", "Human Rights", "Security Studies", "Diplomacy"],
        certifications: ["UPSC CSE", "Public Policy fellowships", "UN programmes", "PG Diplomas (Diplomacy)"],
        topRecruiters: ["MEA (IFS)", "Think Tanks (ORF, CPR, Brookings)", "UN (UNDP, UNESCO)", "NGOs (Amnesty, Greenpeace)", "Political Consultancies"],
        workEnvironment: "Government offices (MEA), think tank offices, UN field/headquarters, or NGO field offices. Involves travel, meetings, and policy writing.",
        governmentJobs: ["IFS (Indian Foreign Service)", "IAS", "IPS", "Defence Services", "Parliamentary Research", "State PSCs"], privateJobs: ["Think Tanks", "Political Consultancy", "Corporate Public Affairs", "Risk Analysis"],
        entrepreneurshipPotential: "Start political consulting firm, policy think tank, or public affairs advisory",
        futureScope: ["India's global role expanding → diplomacy demand", "Policy consulting firms growing", "Climate and tech policy emerging fields", "Think tank sector professionalizing"],
        pros: ["Gateway to diplomacy (IFS)", "Shapes public policy", "Excellent UPSC preparation", "Work at UN / international organizations"], cons: ["Competitive field", "Think tank funding can be political", "Direct corporate path limited", "Government roles need UPSC"],
        category: "Arts", timeToComplete: "3 - 8 years" }
    ),
    // Social Work
    leafNode("arts-social-work", "Social Work & Development", "Create grassroots change — empower communities",
      "Social work is a purpose-driven career for those who want to create social impact. Path: BSW (3yr) or BA + MSW (TISS/Delhi School of Social Work). MSW graduates work with NGOs, UN agencies, CSR departments, hospitals (medical social work), schools, and community development. TISS is India's premier social work institution.",
      "from-emerald-400 to-green-600",
      { iconName: "HeartHandshake", educationPath: ["12th (any stream)", "BSW / BA (3yr)", "MSW (TISS, DSSW, 2yr)", "Field work + specializations"],
        entranceExams: ["TISS NET", "CUET-PG", "Delhi University Entrance"], salaryRanges: { entry: "₹3.5L - ₹8L", mid: "₹8L - ₹18L", senior: "₹18L - ₹40L" }, growthOutlook: "High", topColleges: [{ name: "TISS Mumbai", location: "Mumbai", fees: "₹1L - ₹2L/yr" }, { name: "DSSW Delhi", location: "Delhi", fees: "₹50K - ₹80K/yr" }, { name: "IRMA Anand", location: "Anand", fees: "₹8L - ₹12L total" }],
        skillsRequired: ["Empathy", "Community Organizing", "Counseling", "Project Management", "Grant Writing", "Research & Documentation"],
        specializations: ["Community Development", "Medical Social Work", "Child Protection", "Disability", "Disaster Management", "Corporate CSR", "Rural Development"],
        certifications: ["MSW (Accredited)", "PMRDF Fellowship", "CSR Certification", "Counseling certs"],
        topRecruiters: ["UNICEF", "UNDP", "WHO", "CRY", "Save the Children", "Tata Trusts", "CSR departments (Infosys, Wipro, Tata)"],
        workEnvironment: "Field-based (rural/urban communities), NGO offices, or corporate CSR departments. Emotionally demanding but highly fulfilling. Travel involved.",
        governmentJobs: ["State Social Welfare Depts", "NRLM", "ICDS", "NITI Aayog", "District Administration (Consultant)"], privateJobs: ["NGOs", "CSR (Corporate)", "UN Agencies", "Hospitals (Medical Social Worker)", "Development Consulting (KPMG, PwC)"],
        entrepreneurshipPotential: "Start NGO, social enterprise, CSR consulting firm",
        futureScope: ["CSR mandate (2% of profits) creating jobs in corporates", "UN SDGs driving development funding", "Social entrepreneurship ecosystem growing", "Mental health social work emerging"],
        pros: ["Purpose-driven — create real impact", "Diverse work environments", "Field + office mix (not desk-bound)", "CSR creating corporate social work jobs"], cons: ["Moderate salaries", "Emotionally demanding (trauma exposure)", "Field work in challenging conditions", "NGO funding can be uncertain"],
        category: "Arts", timeToComplete: "3 - 7 years" }
    ),
    // Hotel Management
    leafNode("arts-hotel", "Hotel & Hospitality Management", "Create world-class experiences for global guests",
      "Hotel Management is a professional course covering hotel operations, food production, F&B service, housekeeping, and front office. 3-4 year degree from IHM (NCHMCT JEE) or private institutes. Careers span hotels, resorts, cruise lines, airlines, event management, and QSR chains. India's tourism and hospitality sector is growing rapidly.",
      "from-yellow-400 to-amber-600",
      { iconName: "Utensils", educationPath: ["12th (any stream, 50%+)", "B.Sc Hotel Mgmt (3-4yr) / BHMCT", "Industrial training (6 months)", "Specialization / Management trainee"],
        entranceExams: ["NCHMCT JEE", "IHM Entrance", "AIMA UGAT", "Private college entrances"], salaryRanges: { entry: "₹3L - ₹7L", mid: "₹7L - ₹20L", senior: "₹20L - ₹50L+" }, growthOutlook: "High", topColleges: [{ name: "IHM Pusa Delhi", location: "Delhi", fees: "₹50K - ₹1L/yr" }, { name: "WGSHA Manipal", location: "Manipal", fees: "₹3L - ₹5L/yr" }, { name: "IHM Mumbai", location: "Mumbai", fees: "₹50K - ₹1L/yr" }],
        skillsRequired: ["Customer Service", "Communication", "Food & Beverage Knowledge", "Operations Management", "Teamwork", "Attention to Detail"],
        specializations: ["Hotel Operations", "Food Production (Chef)", "Beverage & Sommelier", "Cruise Line Hospitality", "Aviation Hospitality", "Event Management", "Revenue Management"],
        certifications: ["NCHMCT Degree", "Culinary certification", "Wine & Beverage certs", "Safety & Hygiene (HACCP)"],
        topRecruiters: ["Taj Hotels", "ITC Hotels", "Marriott", "Hyatt", "Oberoi", "Accor", "QSR (Domino's, McDonald's)", "Cruise Lines"],
        workEnvironment: "Hotel/restaurant environment. Shift-based work. Involves standing for long periods. Front-of-house requires grooming standards.",
        governmentJobs: ["ITDC Hotels", "IRCTC", "Government Guest Houses", "Defence Hospitality", "Tourism Departments"], privateJobs: ["Hotels & Resorts", "Cruise Lines", "Airlines", "QSR Chains", "Event Management"],
        entrepreneurshipPotential: "Start restaurant, catering business, boutique hotel, or food truck",
        futureScope: ["India tourism boom (both domestic and international)", "G20/Bharat Mandapam impact", "Cruise tourism growing", "Experiential/luxury travel emerging"],
        pros: ["Global career — work anywhere in the world", "Rapid career growth", "No desk job — dynamic environment", "Restaurant entrepreneurship"], cons: ["Long/irregular hours", "Holiday/weekend work", "Physically demanding", "Lower starting pay"],
        category: "Arts", timeToComplete: "3 - 5 years" }
    ),
    // Fine Arts
    leafNode("arts-fine-arts", "Fine Arts & Visual Arts", "Express yourself through painting, sculpture, and digital art",
      "BFA (Bachelor of Fine Arts) is a 4-year degree covering painting, sculpture, applied art, printmaking, and now digital art/illustration. Careers include professional artist, illustrator, art director, gallery curator, art teacher, and concept artist for games/films. The creative economy and NFTs have opened new revenue streams for artists.",
      "from-red-500 to-rose-700",
      { iconName: "Palette", educationPath: ["12th (any stream)", "BFA (4yr)", "MFA (2yr, for teaching/advancement)", "Portfolio building"],
        entranceExams: ["CUET (Fine Arts)", "College-specific aptitude tests", "NID DAT (relevant skills)"], salaryRanges: { entry: "₹3L - ₹7L", mid: "₹7L - ₹18L", senior: "₹18L - ₹40L+" }, growthOutlook: "High", topColleges: [{ name: "College of Art Delhi", location: "Delhi", fees: "₹20K - ₹40K/yr" }, { name: "JJ School of Art Mumbai", location: "Mumbai", fees: "₹15K - ₹30K/yr" }, { name: "MSU Baroda", location: "Vadodara", fees: "₹20K - ₹50K/yr" }],
        skillsRequired: ["Drawing & Painting", "Creativity", "Color Theory", "Digital Art Software", "3D Modeling (optional)", "Self-Promotion"],
        specializations: ["Painting", "Sculpture", "Applied Art/Graphic Design", "Printmaking", "Digital Illustration", "Concept Art", "Art Education"],
        certifications: ["BFA/MFA degree", "Adobe Suite certifications", "Teaching certifications"],
        topRecruiters: ["Art Galleries", "Gaming Studios (Concept Artist)", "Film Industry (Art Director)", "Advertising Agencies", "Publishing (Illustrator)", "EdTech"],
        workEnvironment: "Studio-based. Freelance is very common. Gaming/film concept artists work in studios. Gallery artists exhibit internationally.",
        governmentJobs: ["College/University Teaching (MFA+NET)", "Lalit Kala Akademi", "Museum Curator"], privateJobs: ["Gaming/Film Studios", "Advertising Agencies", "Publishing Houses", "Art Galleries"],
        entrepreneurshipPotential: "Sell artworks directly (online/galleries/NFTs), start illustration/design studio, teach workshops",
        futureScope: ["NFTs/digital art creating new markets", "Indian art market growing globally", "Concept art demand (gaming, animation, OTT)", "Art therapy emerging field"],
        pros: ["Creative fulfillment", "Freelance independence", "Digital art expanding possibilities", "Global art market accessible"], cons: ["Income can be inconsistent", "Building reputation takes years", "Market-dependent (economic cycles)", "Gallery commissions can be high"],
        category: "Arts", timeToComplete: "4 - 6 years" }
    ),
  ],
};
