import type { DecisionTreeNode } from "../decision-tree.types";
import { leafNode } from "./shared";

// ═══════════════════════════════════════════════
// COMMERCE STREAM
// ═══════════════════════════════════════════════

export const COMMERCE_STREAM: DecisionTreeNode = {
  id: "commerce",
  name: "Commerce Stream",
  shortDescription: "For future business leaders, finance experts, and entrepreneurs",
  detailedDescription: "Commerce is the second most popular stream after Class 10, focusing on business, finance, and economics. Students study Accountancy, Business Studies, Economics, and can opt for Mathematics. This stream opens doors to CA, investment banking, MBA, company secretary, financial analysis, and entrepreneurship. With India becoming a $5 trillion economy, commerce professionals are in massive demand.",
  iconName: "ChartBar",
  color: "from-indigo-600 to-indigo-400",
  educationPath: ["11th-12th Commerce", "B.Com/BBA/Integrated courses", "Professional certs (CA/CS/CMA)", "MBA/PG (optional)"],
  entranceExams: ["CA Foundation", "CS Foundation", "CUET-UG", "IPMAT", "DU JAT", "SET", "NPAT"],
  topColleges: [
    { name: "SRCC Delhi", location: "Delhi", fees: "₹30K - ₹80K/yr" },
    { name: "Christ University", location: "Bangalore", fees: "₹1L - ₹3L/yr" },
    { name: "NMIMS Mumbai", location: "Mumbai", fees: "₹3L - ₹6L/yr" },
    { name: "IIM Indore (IPM)", location: "Indore", fees: "₹4L - ₹6L/yr" },
  ],
  salaryRanges: { entry: "₹4L - ₹10L", mid: "₹10L - ₹30L", senior: "₹30L - ₹1Cr+" },
  growthOutlook: "Very High",
  skillsRequired: ["Financial Analysis", "Business Acumen", "Communication", "Numerical Ability", "Critical Thinking", "Negotiation"],
  specializations: ["Chartered Accountancy", "Investment Banking", "MBA", "Company Secretary", "Financial Analysis", "Actuarial Science"],
  certifications: ["CA", "CS", "CMA", "CFA", "FRM", "ACCA", "CPA"],
  topRecruiters: ["Deloitte", "PwC", "EY", "KPMG", "Goldman Sachs", "HDFC Bank", "ICICI", "Reliance", "McKinsey"],
  workEnvironment: "Corporate offices, banks, consulting firms, or independent practice. Professional and fast-paced.",
  governmentJobs: ["RBI Grade B", "SEBI", "NABARD", "SBI PO", "UPSC (with Commerce optional)", "State PSCs"],
  privateJobs: ["Big 4 Accounting", "Investment Banks", "Corporates (Finance)", "Consulting", "Fintech"],
  researchOpportunities: ["Economic Research", "Financial Research", "PhD in Economics/Finance", "Policy Research"],
  entrepreneurshipPotential: "Start accounting firm, financial advisory, or any business with strong financial foundation. Commerce grads make excellent entrepreneurs.",
  futureScope: ["India becoming $5T economy", "Fintech revolution changing finance", "GST and compliance creating CA demand", "Startup ecosystem needing finance experts"],
  pros: ["High earning potential (especially CA/MBA)", "Versatile — fits every industry", "Can start own practice", "Global career opportunities"],
  cons: ["Professional courses (CA) have low pass rates", "Competitive for top B-schools", "Desk-based work", "Deadline pressure (tax season, month-end)"],
  category: "Commerce",
  timeToComplete: "3-6 years",
  children: [
    // Commerce with Math
    leafNode("commerce-ca", "Chartered Accountant (CA)", "Master of finance, audit, and taxation",
      "CA is one of India's most respected professional qualifications. The ICAI course has 3 levels: Foundation, Intermediate, and Final, plus 3-year articleship training. CAs handle auditing, taxation, financial reporting, and advisory. Pass rate is 5-15%, making it prestigious and high-reward.",
      "from-indigo-500 to-blue-600",
      { iconName: "Calculator", educationPath: ["12th (any stream)", "CA Foundation", "CA Intermediate + 3yr Articleship", "CA Final"], entranceExams: ["CA Foundation", "CA Intermediate", "CA Final"],
        salaryRanges: { entry: "₹6L - ₹10L", mid: "₹15L - ₹30L", senior: "₹50L - ₹1Cr+" }, growthOutlook: "High", topColleges: [{ name: "ICAI", location: "All India", fees: "₹2L - ₹3L total" }],
        skillsRequired: ["Accounting", "Taxation", "Auditing", "Business Laws", "Attention to Detail", "Ethics"],
        specializations: ["Taxation", "Audit & Assurance", "Forensic Accounting", "International Taxation", "GST Advisory", "Insolvency"],
        certifications: ["CA (ICAI)", "DIS (ICAI)", "FAFD", "CPA (US)", "ACCA (UK)"],
        topRecruiters: ["Deloitte", "PwC", "EY", "KPMG", "Reliance", "Tata Group", "ICICI Bank"],
        workEnvironment: "Office-based with client visits. Tax season and audit deadlines can be demanding. Big 4 offers global mobility.",
        governmentJobs: ["CAG", "Income Tax Dept", "RBI", "SEBI", "CBDT", "PSU Audit"],
        privateJobs: ["Big 4 Firms", "Corporates (CFO path)", "Independent Practice"],
        entrepreneurshipPotential: "Start your own CA firm — the most common and profitable path for experienced CAs",
        futureScope: ["GST complexification driving demand", "Forensic accounting growth", "Startup CFO advisory", "IFRS convergence"],
        pros: ["Prestigious qualification", "Own practice independence", "Every business needs a CA", "Global recognition"], cons: ["Low pass rate (5-15%)", "5-6 years to qualify", "Intense articleship", "Tax season pressure"],
        category: "Commerce", timeToComplete: "4.5 - 6 years" }
    ),
    leafNode("commerce-investment-banking", "Investment Banking", "Move billions — shape corporate strategy",
      "Investment bankers help companies raise capital, execute M&A, and provide strategic advisory. Path: Top college (SRCC/St. Stephen's) → MBA from IIM/ISB → IB role. Starting at ₹12-30L, senior MDs earn ₹2-10Cr+. One of India's highest-paying careers.",
      "from-blue-700 to-indigo-600",
      { iconName: "TrendingUp", educationPath: ["12th Commerce (top marks)", "B.Com/BBA from top college", "MBA Finance from IIM/ISB", "Summer internship → IB role"],
        entranceExams: ["CAT (99%ile+)", "GMAT (700+)", "CFA Level 1-3"], salaryRanges: { entry: "₹12L - ₹30L", mid: "₹35L - ₹80L", senior: "₹1Cr - ₹5Cr+" }, growthOutlook: "Very High", topColleges: [{ name: "IIM Ahmedabad", location: "Ahmedabad", fees: "₹12L - ₹25L" }, { name: "ISB Hyderabad", location: "Hyderabad", fees: "₹25L - ₹40L" }],
        skillsRequired: ["Financial Modeling", "Valuation (DCF, LBO)", "Excel & PowerPoint (expert)", "M&A Advisory", "Long work hours endurance"],
        certifications: ["CFA (Chartered Financial Analyst)", "FRM", "Series certifications (US)"],
        topRecruiters: ["Goldman Sachs", "Morgan Stanley", "JP Morgan", "Avendus", "Kotak IB", "JM Financial"],
        workEnvironment: "High-pressure, fast-paced office. 80-100 hour weeks for juniors. Global exposure. Top-tier compensation.",
        governmentJobs: ["SBI Capital Markets", "IDBI Capital", "SEBI"], privateJobs: ["Global Investment Banks", "Boutique IB Firms", "PE/VC Firms"],
        entrepreneurshipPotential: "Start boutique investment bank or PE/VC fund after 10-15 years experience",
        futureScope: ["India IPO market booming", "Startup M&A wave", "PE/VC ecosystem growth", "Cross-border deals rising"],
        pros: ["Highest paying career in India", "Global mobility (Singapore, London, NYC)", "Top-tier network", "Accelerated career growth"], cons: ["80-100 hour work weeks", "Extreme pressure", "Limited personal life for juniors", "Very competitive entry"],
        category: "Commerce", timeToComplete: "6 - 8 years" }
    ),
    leafNode("commerce-mba", "MBA Professional", "Lead, strategize, transform organizations",
      "MBA from a top B-school (IIMs, ISB, XLRI, SPJIMR) opens doors to consulting, product management, marketing, strategy, and general management. Starting packages ₹15-30L at top schools. Best career accelerator for commerce graduates seeking leadership roles.",
      "from-purple-500 to-indigo-500",
      { iconName: "Briefcase", educationPath: ["12th Commerce", "Bachelor (B.Com/BBA)", "Work ex (2-4yr, preferred)", "CAT/XAT → MBA (2yr)"],
        entranceExams: ["CAT", "XAT", "GMAT", "NMAT", "SNAP", "CMAT"], salaryRanges: { entry: "₹15L - ₹30L", mid: "₹30L - ₹60L", senior: "₹60L - ₹2Cr+" }, growthOutlook: "High", topColleges: [{ name: "IIM Ahmedabad", location: "Ahmedabad", fees: "₹12L - ₹25L" }, { name: "XLRI Jamshedpur", location: "Jamshedpur", fees: "₹15L - ₹25L" }, { name: "SPJIMR Mumbai", location: "Mumbai", fees: "₹10L - ₹20L" }],
        skillsRequired: ["Leadership", "Strategic Thinking", "Data Analysis", "Communication", "Networking", "Problem Solving"],
        specializations: ["Marketing", "Finance", "Operations", "HR", "Strategy", "Product Management", "Consulting"],
        certifications: ["Six Sigma", "PMP", "Digital Marketing certs", "Product Management certs"],
        topRecruiters: ["McKinsey", "BCG", "Bain", "Amazon", "Google", "HUL", "P&G", "Tata Group"],
        workEnvironment: "Corporate office, consulting involves travel. Fast-paced, high-stakes decision-making. Excellent networking.",
        governmentJobs: ["PSU Management", "NABARD", "SEBI", "RBI (after MBA)"], privateJobs: ["Consulting", "Product Management", "Corporates", "Startups"],
        entrepreneurshipPotential: "Many MBA grads start ventures — strong network and business skills help raise funding",
        futureScope: ["Digital transformation roles growing", "Startup CXO hiring booming", "ESG/Climate consulting emerging", "Global MBA careers expanding"],
        pros: ["Career accelerator — salary 3-5x pre-MBA", "Versatile across industries", "Strong alumni network", "Leadership fast-track"], cons: ["Expensive (₹15-40L fees)", "Extremely competitive admission", "ROI depends on school tier", "Work-life balance varies"],
        category: "Commerce", timeToComplete: "5 - 7 years (incl work ex)" }
    ),
    leafNode("commerce-cs", "Company Secretary (CS)", "Guardian of corporate governance and compliance",
      "CS is a professional course by ICSI focusing on corporate law, governance, and compliance. Every listed company must have a CS. The 3-level course (CSEET, Executive, Professional) plus training leads to roles in corporate secretarial, legal compliance, and governance advisory.",
      "from-teal-500 to-green-600",
      { iconName: "FileCheck", educationPath: ["12th (any stream)", "CSEET → CS Executive", "CS Professional + Training", "ACS Certification"],
        salaryRanges: { entry: "₹4L - ₹8L", mid: "₹8L - ₹18L", senior: "₹18L - ₹35L+" }, growthOutlook: "High",
        skillsRequired: ["Corporate Law", "Governance", "Compliance", "Drafting", "Meeting Management", "Attention to Detail"],
        certifications: ["CS (ICSI)", "LLB (complementary)", "ICSI Post-Membership courses"],
        topRecruiters: ["Listed Companies", "Law Firms", "PCS Firms", "SEBI", "MCA"],
        workEnvironment: "Corporate office. Regular hours with spikes during board meetings, AGM, and filing deadlines.",
        governmentJobs: ["MCA", "SEBI", "Stock Exchanges", "ROC Offices"], privateJobs: ["Listed Companies", "Law Firms", "Practicing CS"],
        entrepreneurshipPotential: "Start independent Company Secretary practice (PCS) — stable, respected profession",
        futureScope: ["Companies Act compliance growing", "Startup IPOs needing CS", "ESG governance expanding", "NCLT/NCLAT matters rising"],
        pros: ["Every listed company needs one", "Work-life balance", "Can practice independently", "Respected governance role"], cons: ["Lower salary ceiling vs CA", "Limited global recognition", "Exam pass rates moderate"],
        category: "Commerce", timeToComplete: "3 - 5 years" }
    ),
    leafNode("commerce-cfa", "Financial Analyst (CFA)", "Master investments and portfolio management",
      "CFA (Chartered Financial Analyst) is the gold standard for investment professionals. The 3-level exam covers equity research, portfolio management, fixed income, derivatives, and ethics. CFAs work in asset management, equity research, hedge funds, and private equity.",
      "from-amber-500 to-orange-500",
      { iconName: "LineChart", educationPath: ["12th Commerce", "B.Com/BBA", "CFA Level 1-3 (while working)", "MBA optional"],
        entranceExams: ["CFA Level 1", "CFA Level 2", "CFA Level 3"], salaryRanges: { entry: "₹6L - ₹15L", mid: "₹15L - ₹35L", senior: "₹35L - ₹1Cr+" }, growthOutlook: "Very High",
        skillsRequired: ["Financial Analysis", "Equity Research", "Portfolio Management", "Excel/Financial Modeling", "Valuation", "Investment Writing"],
        certifications: ["CFA", "FRM", "CAIA", "CIPM"],
        topRecruiters: ["BlackRock", "Fidelity", "ICICI Prudential", "SBI Mutual Fund", "Motilal Oswal", "CRISIL"],
        workEnvironment: "Office-based. Research-oriented, market-hours aligned. Intellectually stimulating with continuous learning.",
        governmentJobs: ["RBI", "SEBI", "LIC", "PFRDA"], privateJobs: ["Mutual Funds", "Hedge Funds", "PE/VC", "Banks", "Wealth Management"],
        entrepreneurshipPotential: "Start own RIA (Registered Investment Advisor) or PMS (Portfolio Management Services)",
        futureScope: ["Indian capital markets deepening", "Retail investing boom", "ESG investing trend", "Algo/AI-driven investing"],
        pros: ["Globally recognized certification", "High earning potential", "Intellectually challenging", "Multiple industry options"], cons: ["CFA takes 3-4 years to complete", "Low pass rates per level (~40%)", "Job market competitive", "Continuous learning required"],
        category: "Commerce", timeToComplete: "5 - 7 years" }
    ),
    leafNode("commerce-banking", "Banking & Financial Services", "The backbone of the economy",
      "Banking careers span public sector (SBI PO, IBPS), private banks (HDFC, ICICI, Axis), and fintech. Roles include relationship management, credit analysis, treasury, and operations. Bank PO exams are one of India's largest recruitment drives with excellent job security.",
      "from-blue-500 to-cyan-500",
      { iconName: "Landmark", educationPath: ["12th Commerce (60%+)", "B.Com/BBA", "Bank PO exams (SBI/IBPS/RBI)", "MBA for faster growth"],
        entranceExams: ["SBI PO", "IBPS PO", "RBI Grade B", "RBI Assistant", "NABARD"], salaryRanges: { entry: "₹5L - ₹8L", mid: "₹10L - ₹20L", senior: "₹20L - ₹40L+" }, growthOutlook: "Stable",
        skillsRequired: ["Financial Products", "Customer Service", "Credit Analysis", "Regulatory Knowledge", "Sales", "Risk Management"],
        topRecruiters: ["SBI", "HDFC Bank", "ICICI Bank", "Axis Bank", "Kotak Mahindra", "Yes Bank"],
        workEnvironment: "Bank branch or corporate office. Regular banking hours. PSU banks offer excellent work-life balance.",
        governmentJobs: ["SBI PO/Clerk", "IBPS PO/Clerk", "RBI Grade B/Officer", "NABARD", "SIDBI"], privateJobs: ["Private Banks", "NBFCs", "Fintech", "Payment Companies"],
        entrepreneurshipPotential: "Start NBFC, microfinance institution, or fintech startup",
        futureScope: ["Digital banking transformation", "Fintech-bank partnerships", "Financial inclusion drive", "Banking-as-a-Service"],
        pros: ["Job security (especially PSU)", "Structured career progression", "Good perks (loans, pension)", "Transferable skills"], cons: ["Transferable job in PSU banks", "Sales targets in private banks", "Bureaucracy in PSUs", "Branch postings may be rural"],
        category: "Commerce", timeToComplete: "3 - 5 years" }
    ),
    leafNode("commerce-actuarial", "Actuarial Science", "Predict risk — shape insurance and finance",
      "Actuaries use math, statistics, and financial theory to assess risk for insurance, pensions, and investments. One of the highest paying professions globally. The actuarial exams (by IAI/IFoA) are extremely rigorous — only 300-400 qualified actuaries in India, creating massive demand.",
      "from-violet-500 to-purple-600",
      { iconName: "Sigma", educationPath: ["12th Commerce with Math (70%+)", "B.Sc Actuarial Science / B.Com", "Clear actuarial papers (IAI/IFoA)", "Fellowship (FIAI/FIA)"],
        salaryRanges: { entry: "₹8L - ₹15L", mid: "₹15L - ₹40L", senior: "₹40L - ₹1.5Cr+" }, growthOutlook: "Very High",
        skillsRequired: ["Advanced Mathematics", "Probability & Statistics", "Financial Mathematics", "Risk Modeling", "R/Python", "Excel (Advanced)"],
        specializations: ["Life Insurance", "General Insurance", "Pension", "Enterprise Risk Management", "Health Insurance"],
        certifications: ["ACET (India Entry)", "IAI Papers (CT, CA, ST, SA series)", "IFoA (UK pathway)", "SOA/CAS (US pathway)"],
        topRecruiters: ["LIC", "ICICI Prudential", "Munich Re", "Swiss Re", "Mercer", "Aon", "WTW"],
        workEnvironment: "Office-based. Quantitative, analytical work. Low stress, high prestige. Global mobility.",
        governmentJobs: ["LIC", "IRDAI", "RBI", "GIC Re"], privateJobs: ["Insurance Companies", "Reinsurance", "Consulting", "Banks (Risk)"],
        entrepreneurshipPotential: "Start actuarial consulting firm or insure-tech startup",
        futureScope: ["Insurance penetration in India just 4% — huge growth potential", "IRDAI regulatory requirements expanding", "Data-driven actuarial models", "Insure-tech boom"],
        pros: ["Extremely high salary", "Global profession (work anywhere)", "Low competition (only ~400 in India)", "Excellent work-life balance"], cons: ["Very difficult exams (8-10 years to qualify)", "Highly specialized — limited lateral moves", "Niche job market in India", "Mathematically intensive"],
        category: "Commerce", timeToComplete: "8 - 10 years" }
    ),
    // Commerce without Math options
    leafNode("commerce-bba", "BBA & Management Studies", "Foundation for business leadership",
      "BBA (3 years) or integrated BBA+MBA (IPM from IIMs, 5 years) builds business fundamentals — marketing, finance, HR, operations, and strategy. Strong platform for MBA or direct corporate entry. IPM from IIM Indore/Rohtak is the premier integrated management program in India.",
      "from-cyan-400 to-blue-500",
      { iconName: "Building", educationPath: ["12th Commerce", "BBA/IPM (3-5yr)", "MBA (optional)"],
        entranceExams: ["IPMAT (IIM Indore/Rohtak)", "DU JAT", "SET", "NPAT", "CUET-UG"], salaryRanges: { entry: "₹4L - ₹8L", mid: "₹10L - ₹25L", senior: "₹25L - ₹50L+" }, growthOutlook: "High",
        topColleges: [{ name: "IIM Indore (IPM)", location: "Indore", fees: "₹4L - ₹6L/yr" }, { name: "NMIMS Mumbai", location: "Mumbai", fees: "₹3L - ₹6L/yr" }, { name: "Christ University", location: "Bangalore", fees: "₹1L - ₹3L/yr" }],
        skillsRequired: ["Business Fundamentals", "Communication", "Excel/PowerPoint", "Teamwork", "Presentation"],
        specializations: ["Marketing", "Finance", "HR", "Operations", "International Business", "Digital Business"],
        topRecruiters: ["Deloitte", "KPMG", "HUL", "ICICI", "Flipkart", "Amazon", "Tata Group"],
        workEnvironment: "Corporate offices across sectors. Fast-paced, collaborative. Good career progression.",
        governmentJobs: ["Bank PO", "SSC", "Defence (AFCAT)"], privateJobs: ["Corporates", "Startups", "Consulting", "Banking"],
        entrepreneurshipPotential: "BBA provides strong foundation for starting and managing a business",
        futureScope: ["India corporate sector growing", "Startup ecosystem expanding", "Professional management demand"],
        pros: ["Broad business foundation", "MBA fast-track (IPM)", "Diverse career options"], cons: ["Lower starting salary than tech", "MBA often needed for top roles", "Competitive for top colleges"],
        category: "Commerce", timeToComplete: "3 - 5 years" }
    ),
    leafNode("commerce-economics", "Economics (Hons)", "Decode the forces that shape markets and nations",
      "B.A./B.Sc Economics (Hons) from top colleges (SRCC, St. Stephen's, LSR) leads to careers in government, banking, think tanks, multilateral organizations, and corporate strategy. With strong quantitative focus, economics graduates are valued for analytical and policy thinking.",
      "from-emerald-500 to-green-600",
      { iconName: "Globe", educationPath: ["12th Commerce (Math recommended)", "B.A./B.Sc Economics Hons (3yr)", "M.A./M.Sc Economics (2yr)", "Ph.D for research/WB/IMF"],
        entranceExams: ["CUET-UG", "RBI Grade B", "IES (Indian Economic Service)"], salaryRanges: { entry: "₹6L - ₹12L", mid: "₹12L - ₹25L", senior: "₹25L - ₹60L+" }, growthOutlook: "High",
        topColleges: [{ name: "SRCC Delhi", location: "Delhi", fees: "₹30K - ₹80K/yr" }, { name: "St. Stephen's Delhi", location: "Delhi", fees: "₹50K - ₹1L/yr" }, { name: "Ashoka University", location: "Sonipat", fees: "₹4L - ₹8L/yr" }],
        skillsRequired: ["Econometrics", "Statistical Analysis (R/STATA)", "Policy Analysis", "Research Writing", "Critical Thinking"],
        certifications: ["IES", "RBI Grade B", "CFA", "FRM"],
        topRecruiters: ["RBI", "NITI Aayog", "World Bank (YPP)", "IMF", "CRISIL", "S&P Global", "Goldman Sachs Research"],
        workEnvironment: "Office/research environment. Regular hours. RBI and multilaterals offer excellent benefits and global exposure.",
        governmentJobs: ["RBI", "NITI Aayog", "IES", "SEBI", "NABARD", "State Planning"], privateJobs: ["Banking Research", "Think Tanks", "Corporates (Strategy)", "Consulting"],
        entrepreneurshipPotential: "Start economic consulting firm, policy think tank, or data analytics venture",
        futureScope: ["Data-driven economic policy", "ESG and climate economics growing", "Fintech policy roles", "International development careers"],
        pros: ["Prestigious government roles (RBI/IES)", "Strong analytical foundation", "Global organization careers", "Policy impact potential"], cons: ["Math-intensive", "Top college dependency", "Limited entry-level corporate roles", "Ph.D needed for IMF/WB"],
        category: "Commerce", timeToComplete: "3 - 7 years" }
    ),
    leafNode("commerce-cma", "Cost & Management Accountant (CMA)", "Optimize costs — drive business efficiency",
      "CMA (formerly ICWA) by ICAI focuses on cost accounting, management accounting, and business strategy. CMAs work in manufacturing, services, and consulting, driving cost optimization and profitability. The course has 3 levels and is less competitive than CA.",
      "from-orange-400 to-amber-500",
      { iconName: "PieChart", educationPath: ["12th Commerce", "CMA Foundation", "CMA Intermediate + Training", "CMA Final"],
        salaryRanges: { entry: "₹4L - ₹7L", mid: "₹7L - ₹18L", senior: "₹18L - ₹35L" }, growthOutlook: "High",
        skillsRequired: ["Cost Accounting", "Management Accounting", "Budgeting", "Variance Analysis", "ERP Systems", "Strategic Planning"],
        certifications: ["CMA (ICAI)", "ACMA (CIMA UK)", "CGMA"],
        topRecruiters: ["Manufacturing Companies", "IT Services", "PSUs", "Consulting Firms"],
        workEnvironment: "Corporate office or factory cost department. Manufacturing exposure. Good work-life balance.",
        governmentJobs: ["PSU Cost Departments", "Defence Accounts", "Indian Cost Accounts Service"], privateJobs: ["Manufacturing", "IT Services", "Consulting"],
        entrepreneurshipPotential: "Start cost consultancy firm — many SMEs need cost optimization",
        futureScope: ["Make in India boosting manufacturing", "Cost competitiveness focus", "ERP/SAP specialization", "GST and transfer pricing"],
        pros: ["Less competitive than CA", "Manufacturing sector core", "Good work-life balance", "Strategic role"], cons: ["Lower recognition than CA", "Manufacturing-centric", "Limited global recognition"],
        category: "Commerce", timeToComplete: "3.5 - 5 years" }
    ),
  ],
};
