import type { DecisionTreeNode } from "../decision-tree.types";
import { leafNode } from "./shared";

// ═══════════════════════════════════════════════
// DIPLOMA / POLYTECHNIC STREAM
// ═══════════════════════════════════════════════

export const DIPLOMA_STREAM: DecisionTreeNode = {
  id: "diploma",
  name: "Diploma / Polytechnic",
  shortDescription: "Hands-on technical education — become job-ready in 3 years",
  detailedDescription: "A Diploma (Polytechnic) is a 3-year technical program after Class 10 that makes you job-ready faster than the 12th + degree route. Diplomas are offered in engineering branches (Mechanical, Civil, Electrical, CS, ECE), pharmacy, and specialized fields. After diploma, students can join the workforce, start a business, or take lateral entry into 2nd year of B.Tech (via LEET). Diploma holders are valued for practical skills and are in high demand in manufacturing, construction, IT support, and government technical departments.",
  iconName: "Wrench",
  color: "from-amber-600 to-amber-400",
  educationPath: ["10th Pass (Maths & Science)", "Diploma / Polytechnic (3yr)", "Job / Lateral B.Tech (LEET)", "B.Tech (3yr, if lateral entry)"],
  entranceExams: ["Polytechnic CET (state-wise)", "JEECUP (UP)", "Delhi CET", "AP POLYCET", "TS POLYCET", "Private college entrances"],
  topColleges: [
    { name: "Government Polytechnic Mumbai", location: "Mumbai", fees: "₹5K - ₹15K/yr" },
    { name: "Pusa Polytechnic Delhi", location: "Delhi", fees: "₹10K - ₹20K/yr" },
    { name: "SJ Polytechnic Bangalore", location: "Bangalore", fees: "₹15K - ₹30K/yr" },
  ],
  salaryRanges: { entry: "₹2.5L - ₹5L", mid: "₹5L - ₹12L", senior: "₹12L - ₹25L" },
  growthOutlook: "High",
  skillsRequired: ["Practical/Hands-on Skills", "Technical Drawing", "Workshop Practice", "Basic Engineering Knowledge", "Problem Solving"],
  specializations: ["Mechanical", "Civil", "Electrical", "CS/IT", "ECE", "Automobile", "Chemical", "Mining"],
  certifications: ["Diploma (State Board)", "LEET (for B.Tech lateral)", "Skill India certifications", "ITI add-on certs"],
  topRecruiters: ["L&T", "Tata Motors", "BHEL", "PSUs", "Construction Companies", "IT Services (Support)", "Manufacturing"],
  workEnvironment: "Factory floor, construction site, workshop, or IT support office. Hands-on, practical work. Less desk-bound than degree engineers.",
  governmentJobs: ["Junior Engineer (JE) — SSC JE, RRB JE, State PSC JE", "PSU Technician", "Defence (Navy/IAF Technical)", "State Electricity Boards", "PWD/CPWD"],
  privateJobs: ["Manufacturing Plants", "Construction Companies", "Automobile Industry", "IT Support", "Maintenance"],
  researchOpportunities: ["Limited — research path typically requires B.Tech → M.Tech → Ph.D", "Diploma + experience can lead to supervisor/manager roles"],
  entrepreneurshipPotential: "Start fabrication workshop, electrical contracting, auto repair garage, or small-scale manufacturing unit. Diploma gives practical skills to run a technical business.",
  futureScope: ["Make in India driving manufacturing jobs", "EV industry creating new technician roles", "Smart city construction demand", "Solar/renewable energy installation"],
  pros: ["Job-ready in 3 years (vs 6+ for degree)", "Practical/hands-on focus", "Lower education cost", "Lateral B.Tech entry option", "Government JE jobs accessible"],
  cons: ["Lower salary ceiling than degree holders", "Limited research/R&D roles", "Perceived as 'less than' degree (though unfair)", "Promotion to senior roles may require B.Tech"],
  category: "Diploma",
  timeToComplete: "3 years",
  children: [
    leafNode("diploma-mechanical", "Diploma in Mechanical Engineering", "Design, manufacture, and maintain machines and systems",
      "3-year diploma covering manufacturing processes, thermal engineering, machine design, CAD/CAM, CNC, automobile basics, and workshop practice. Graduates work as junior engineers, CNC programmers, maintenance supervisors, and quality control inspectors in automobile, manufacturing, and process industries.",
      "from-slate-600 to-slate-400",
      { iconName: "Cog", educationPath: ["10th (Maths & Science)", "Diploma Mechanical (3yr)", "JE job or LEET → B.Tech (3yr)"],
        salaryRanges: { entry: "₹2.5L - ₹4.5L", mid: "₹4.5L - ₹10L", senior: "₹10L - ₹20L" }, growthOutlook: "High",
        skillsRequired: ["Workshop Skills", "CAD/CAM", "CNC Programming", "Technical Drawing", "Quality Control"],
        specializations: ["CNC Machining", "Automobile Tech", "CAD/CAM", "Welding & Fabrication", "Maintenance Engineering"],
        topRecruiters: ["Tata Motors", "Maruti Suzuki", "L&T", "BHEL", "Hero MotoCorp", "Mahindra & Mahindra"],
        workEnvironment: "Factory floor, workshop, or manufacturing plant. Hands-on with machinery. May involve shifts in production environments.",
        governmentJobs: ["JE (Mechanical) — SSC JE, RRB JE", "PSU (BHEL, NTPC Technician)", "Ordnance Factories", "Metro Rail Corps"], privateJobs: ["Automobile Industry", "Manufacturing", "CNC Shops", "Maintenance Services"],
        entrepreneurshipPotential: "Start CNC job shop, auto repair garage, fabrication unit, or small-scale manufacturing",
        futureScope: ["Manufacturing hub growth", "EV automobile revolution", "Additive manufacturing", "Industry 4.0 automation"],
        pros: ["Always in demand (core engineering)", "Broad industry applicability", "Strong hands-on foundation", "Entrepreneurship-friendly"], cons: ["Factory/shop environment", "Physically demanding", "Salary growth slower than CS", "Limited desk/WFH roles"],
        category: "Diploma", timeToComplete: "3 years" }
    ),
    leafNode("diploma-civil", "Diploma in Civil Engineering", "Build the nation — roads, bridges, buildings",
      "3-year diploma covering surveying, construction materials, structural design, estimation & costing, AutoCAD, and construction management. Diploma holders work as site supervisors, junior engineers, surveyors, and estimators in construction companies, PWD, and real estate firms.",
      "from-amber-600 to-yellow-500",
      { iconName: "HardHat", educationPath: ["10th (Maths & Science)", "Diploma Civil (3yr)", "JE job or LEET → B.Tech (3yr)"],
        salaryRanges: { entry: "₹2.5L - ₹4.5L", mid: "₹4.5L - ₹10L", senior: "₹10L - ₹20L" }, growthOutlook: "Very High",
        skillsRequired: ["Surveying", "AutoCAD", "Estimation & Costing", "Construction Management", "Material Testing"],
        specializations: ["Surveying", "Construction Technology", "Quantity Surveying", "Transportation Engineering", "Water Resources"],
        topRecruiters: ["L&T Construction", "Shapoorji Pallonji", "DLF", "Tata Projects", "Gammon India", "PWD/CPWD"],
        workEnvironment: "Active construction sites — outdoor work. Involves supervising workers, inspecting quality, managing materials. Site-based, may require relocation.",
        governmentJobs: ["JE (Civil) — SSC JE, RRB JE, State PSC JE", "PWD/CPWD", "Municipal Corporations", "NHAI"], privateJobs: ["Construction Companies", "Real Estate Developers", "Infrastructure Projects", "Consultancy Firms"],
        entrepreneurshipPotential: "Start construction contracting business, surveying consultancy, or building material supply",
        futureScope: ["Infrastructure boom ($1.4T National Infrastructure Pipeline)", "Smart cities mission", "Real estate sector growth", "Green building certification demand"],
        pros: ["Infrastructure boom = massive demand", "Government JE jobs plentiful", "Can start own contracting business", "See tangible results of your work"], cons: ["Site work — outdoors, dusty, hot", "Project-based — may relocate often", "Physically demanding", "Safety risks at construction sites"],
        category: "Diploma", timeToComplete: "3 years" }
    ),
    leafNode("diploma-electrical", "Diploma in Electrical Engineering", "Power the world — generation to distribution",
      "3-year diploma covering electrical machines, power systems, control systems, PLC/SCADA, wiring & installation, and maintenance. Graduates work in power plants, substations, electrical contracting, manufacturing plants, and renewable energy companies.",
      "from-yellow-500 to-amber-500",
      { iconName: "Zap", educationPath: ["10th (Maths & Science)", "Diploma Electrical (3yr)", "JE job or LEET → B.Tech (3yr)"],
        salaryRanges: { entry: "₹2.5L - ₹5L", mid: "₹5L - ₹10L", senior: "₹10L - ₹22L" }, growthOutlook: "High",
        skillsRequired: ["Electrical Circuits", "PLC/SCADA", "Wiring & Installation", "Motor/Generator knowledge", "Safety Protocols"],
        specializations: ["Power Systems", "Industrial Automation", "Renewable Energy", "Electrical Maintenance", "Building Electrification"],
        topRecruiters: ["State Electricity Boards", "NTPC", "Power Grid", "BHEL", "Siemens", "ABB", "Schneider Electric"],
        workEnvironment: "Power plants, substations, industrial electrical rooms, or site-based (electrical contracting). Safety-critical — protocols essential.",
        governmentJobs: ["JE (Electrical) — SSC JE, RRB JE", "State Electricity Boards", "Metro Rail Corps", "Defence Technical"], privateJobs: ["Power Companies", "Manufacturing (Electrical Maintenance)", "Construction (Electrical Contracting)", "Automation Companies"],
        entrepreneurshipPotential: "Start electrical contracting firm, solar installation business, or electrical panel manufacturing",
        futureScope: ["Renewable energy (solar/wind) explosion", "EV charging infrastructure", "Smart grid modernization", "Industrial IoT automation"],
        pros: ["Core sector — always essential", "Renewable energy growth", "Government jobs stable", "Contracting business potential"], cons: ["Electrical hazards (safety training critical)", "May involve heights/outdoors", "Shift work in some roles", "Lower starting pay than CS fields"],
        category: "Diploma", timeToComplete: "3 years" }
    ),
    leafNode("diploma-cs", "Diploma in Computer Science / IT", "Build software, manage networks, provide IT support",
      "3-year diploma covering programming (C, Java, Python, web), databases, networking, and IT infrastructure. Diploma holders work as junior developers, IT support engineers, network technicians, and system administrators. Can take lateral entry to B.Tech CSE for deeper knowledge and higher packages.",
      "from-blue-600 to-cyan-400",
      { iconName: "Monitor", educationPath: ["10th (Maths & Science)", "Diploma CS/IT (3yr)", "Job or LEET → B.Tech CSE (3yr)"],
        salaryRanges: { entry: "₹2.5L - ₹5L", mid: "₹5L - ₹12L", senior: "₹12L - ₹25L+" }, growthOutlook: "Very High",
        skillsRequired: ["Programming (C/Java/Python/JavaScript)", "Databases (SQL)", "Networking Basics", "Web Development", "Linux"],
        specializations: ["Web Development", "Network Administration", "Cybersecurity", "Cloud Computing", "Mobile App Development"],
        topRecruiters: ["TCS", "Infosys", "Wipro", "HCL", "Tech Mahindra", "Startups", "IT Support Companies"],
        workEnvironment: "Office/IT park. Air-conditioned. Desk work. Software roles can be remote. IT support may involve site visits.",
        governmentJobs: ["JE (IT) — Limited", "SSC", "State IT Departments", "Banking IT Support"], privateJobs: ["IT Services", "Software Companies", "Startups", "Tech Support"],
        entrepreneurshipPotential: "Start web development agency, IT support business, or SaaS product company",
        futureScope: ["IT sector in India still booming", "Cloud computing demand", "Cybersecurity roles growing", "AI/ML tools accessible to diploma holders"],
        pros: ["Fastest growing sector", "Office environment", "Remote work possible", "Lateral B.Tech path to FAANG"], cons: ["Rapid technology changes (continuous learning)", "Entry-level competition high", "Diploma ceiling for certain roles", "Core CS theory may need B.Tech"],
        category: "Diploma", timeToComplete: "3 years" }
    ),
    leafNode("diploma-ece", "Diploma in Electronics & Communication", "Build circuits, communication systems, and embedded devices",
      "3-year diploma covering analog/digital electronics, microcontrollers, embedded systems, communication systems, and PCB design. Graduates work as electronics technicians, embedded developers, telecom field engineers, and IoT developers in electronics manufacturing, telecom, and consumer electronics industries.",
      "from-violet-500 to-purple-400",
      { iconName: "Cpu", educationPath: ["10th (Maths & Science)", "Diploma ECE (3yr)", "Job or LEET → B.Tech (3yr)"],
        salaryRanges: { entry: "₹2.5L - ₹4.5L", mid: "₹4.5L - ₹10L", senior: "₹10L - ₹22L" }, growthOutlook: "High",
        skillsRequired: ["Circuit Analysis", "Microcontroller Programming", "PCB Design", "Embedded Systems", "Soldering & Testing"],
        specializations: ["Embedded Systems", "IoT", "VLSI", "Telecom", "Consumer Electronics"],
        topRecruiters: ["Samsung", "LG", "Sony", "Havells", "Bajaj Electricals", "Telecom Companies (Jio, Airtel)", "EMS (Foxconn)"],
        workEnvironment: "Electronics lab, factory floor (PCB assembly), or telecom field (tower maintenance). Mix of desk and hands-on.",
        governmentJobs: ["BSNL/MTNL Technician", "DRDO Technical", "ISRO Technical Assistant", "Railways (S&T)"], privateJobs: ["Electronics Manufacturing", "Telecom Companies", "Consumer Electronics", "Embedded Systems Firms"],
        entrepreneurshipPotential: "Start electronics repair/service center, PCB assembly unit, IoT product company",
        futureScope: ["Semiconductor manufacturing push", "IoT explosion", "5G/6G telecom rollout", "Drone/UAV electronics"],
        pros: ["Electronics in everything (IoT)", "Semiconductor push creating jobs", "Hands-on, practical field", "Government DRDO/ISRO jobs"], cons: ["Rapid tech obsolescence", "Manufacturing jobs shifting", "Lower pay than pure CS", "Complex troubleshooting"],
        category: "Diploma", timeToComplete: "3 years" }
    ),
    leafNode("diploma-automobile", "Diploma in Automobile Engineering", "Design, service, and maintain vehicles — from ICE to EV",
      "3-year diploma covering automobile engines, vehicle dynamics, auto electrical, EV technology, garage/service management, and diagnostics. With India becoming a global automobile hub and EV revolution unfolding, automobile diploma holders are in high demand at OEMs, dealerships, and EV startups.",
      "from-red-500 to-orange-600",
      { iconName: "Car", educationPath: ["10th (Maths & Science)", "Diploma Automobile (3yr)", "Job or LEET → B.Tech (3yr)"],
        salaryRanges: { entry: "₹2.5L - ₹4.5L", mid: "₹4.5L - ₹10L", senior: "₹10L - ₹20L" }, growthOutlook: "Very High",
        skillsRequired: ["Auto Mechanics", "Engine Diagnostics", "Auto CAD", "EV Basics", "Vehicle Electronics"],
        specializations: ["EV Technology", "Automobile Servicing", "Vehicle Design (CAD)", "Motorsports", "Fleet Management"],
        topRecruiters: ["Tata Motors", "Maruti Suzuki", "Mahindra", "Ola Electric", "Ather Energy", "Hero MotoCorp", "Toyota", "Hyundai"],
        workEnvironment: "Dealership service center, automobile plant, or design office. Hands-on vehicle work. EV startups offer modern facilities.",
        governmentJobs: ["State Transport Depts (Technical)", "Defence (EME Corps)", "PSU (BHEL/BEML)", "Municipal Transport"], privateJobs: ["OEM Plants", "Dealerships (Service Manager)", "EV Companies", "Fleet Operators"],
        entrepreneurshipPotential: "Start auto repair garage, EV service center, auto spare parts business, or dealership",
        futureScope: ["EV revolution — massive retraining/create demand", "India as global auto hub", "Connected/autonomous vehicles", "Battery swapping/charging infra"],
        pros: ["EV boom creating new career paths", "Always needed (everyone has vehicles)", "Garage ownership business potential", "India auto hub = more jobs"], cons: ["ICE to EV transition — need to reskill", "Garage work physically demanding", "Dealership hours may include weekends", "Largely manufacturing/service — limited R&D"],
        category: "Diploma", timeToComplete: "3 years" }
    ),
    leafNode("diploma-pharmacy", "Diploma in Pharmacy (D.Pharm)", "The gateway to the pharmaceutical profession",
      "D.Pharm is a 2-year diploma after 10th or 12th to become a registered pharmacist. Course covers pharmaceutics, pharmaceutical chemistry, pharmacology, and drug store management. After D.Pharm, you can work as a pharmacist in hospitals, medical stores, or pharmaceutical companies. Can also pursue B.Pharm via lateral entry.",
      "from-green-500 to-emerald-600",
      { iconName: "Pill", educationPath: ["10th / 12th (Science)", "D.Pharm (2yr)", "Registered Pharmacist", "B.Pharm lateral (optional)"],
        salaryRanges: { entry: "₹2L - ₹4L", mid: "₹4L - ₹8L", senior: "₹8L - ₹15L" }, growthOutlook: "High",
        skillsRequired: ["Drug Knowledge", "Pharmaceutical Chemistry", "Prescription Reading", "Inventory Management", "Customer Interaction"],
        specializations: ["Hospital Pharmacy", "Community Pharmacy", "Industrial Pharmacy", "Drug Regulatory Affairs"],
        topRecruiters: ["Apollo Pharmacy", "MedPlus", "Pharma Companies (Cipla, Sun Pharma)", "Hospitals", "Government Medical Stores"],
        workEnvironment: "Pharmacy/medical store counter or hospital pharmacy. Clean, indoor environment. Interact with patients and doctors.",
        governmentJobs: ["Government Hospital Pharmacist", "Railway/Defence Medical Stores", "State Drug Control"], privateJobs: ["Retail Pharmacy Chains", "Hospital Pharmacy", "Pharma Manufacturing", "Medical Representatives"],
        entrepreneurshipPotential: "Open own medical store/pharmacy — one of the most common and profitable small businesses in India",
        futureScope: ["Pharmacy chains expanding rapidly", "Online pharmacy (PharmEasy, 1mg) growth", "Government Jan Aushadhi Kendras", "Pharma industry growth"],
        pros: ["Short course (2 years)", "Can open own pharmacy", "Recession-proof (healthcare)", "Respectable profession"], cons: ["Lower salary ceiling", "Needs B.Pharm for pharma industry roles", "Standing for long hours", "Inventory management stress"],
        category: "Diploma", timeToComplete: "2 - 3 years" }
    ),
    leafNode("diploma-textile", "Diploma in Textile Technology", "From fiber to fashion — master textile processes",
      "3-year diploma covering textile fibers, yarn manufacturing, fabric production, dyeing/printing, quality control, and garment technology. India has a massive textile industry — the second largest employer after agriculture. Graduates work in textile mills, garment export houses, and fashion brands.",
      "from-pink-400 to-rose-400",
      { iconName: "Shirt", educationPath: ["10th (Maths & Science)", "Diploma Textile (3yr)", "Job or LEET → B.Tech Textile (3yr)"],
        salaryRanges: { entry: "₹2L - ₹4L", mid: "₹4L - ₹8L", senior: "₹8L - ₹18L" }, growthOutlook: "Moderate",
        skillsRequired: ["Textile Processing", "Quality Testing", "Dyeing/Chemical Knowledge", "Production Management"],
        specializations: ["Spinning", "Weaving", "Processing/Dyeing", "Garment Manufacturing", "Technical Textiles"],
        topRecruiters: ["Arvind Mills", "Raymond", "Vardhman", "Welspun", "Trident", "Aditya Birla (Grasim)", "Shahi Exports"],
        workEnvironment: "Textile mill or garment factory. Involves managing production lines and quality checks. May be in textile hubs (Tirupur, Ludhiana, Surat).",
        governmentJobs: ["NTC Mills", "State Textile Corporations", "KVIC", "Textile Ministry"], privateJobs: ["Textile Mills", "Garment Export Houses", "Fashion Brands", "Quality Inspection"],
        entrepreneurshipPotential: "Start garment manufacturing, textile trading, dyeing unit, or boutique brand",
        futureScope: ["PLI scheme for textiles", "Technical textiles (medical, industrial)", "Sustainable/Eco-friendly textiles", "India as China+1 textile hub"],
        pros: ["India textile hub = large job market", "Can start own unit", "PLI scheme driving investment"], cons: ["Concentrated in textile hubs", "Export market dependent", "Competitive from Bangladesh/Vietnam"],
        category: "Diploma", timeToComplete: "3 years" }
    ),
  ],
};
