import type { DecisionTreeNode } from "../decision-tree.types";
import { leafNode } from "./shared";

// ═══════════════════════════════════════════════
// ITI (Industrial Training Institute) STREAM
// ═══════════════════════════════════════════════

export const ITI_STREAM: DecisionTreeNode = {
  id: "iti",
  name: "ITI (Industrial Training)",
  shortDescription: "Master a trade — become a skilled technician in 1-2 years",
  detailedDescription: "ITI courses are short-term (6 months to 2 years) skill-based training programs after Class 10. They focus 100% on practical, hands-on skills that make you immediately employable. ITI graduates are called 'craftsmen' and work in manufacturing, construction, automotive repair, electrical work, and electronics servicing. Government ITIs are heavily subsidized (fees as low as ₹500-2000/year). The Skill India mission and international demand for Indian skilled workers (Gulf, Europe, Japan) have elevated ITI careers.",
  iconName: "Wrench",
  color: "from-orange-600 to-orange-400",
  educationPath: ["10th Pass", "ITI (6mo - 2yr)", "Apprenticeship (1yr)", "Job / AITT → National Trade Cert"],
  entranceExams: ["ITI Admission (Merit-based in 10th marks)", "NCVT SCVT entrance (state-wise)", "Walk-in (private ITIs)"],
  topColleges: [
    { name: "Government ITI (major cities)", location: "Various", fees: "₹500 - ₹2K/yr" },
    { name: "ATI Mumbai", location: "Mumbai", fees: "₹2K - ₹5K/yr" },
    { name: "NSTI (Various)", location: "Multiple", fees: "₹1K - ₹5K/yr" },
  ],
  salaryRanges: { entry: "₹2L - ₹4L", mid: "₹4L - ₹8L", senior: "₹8L - ₹15L" },
  growthOutlook: "High",
  skillsRequired: ["Practical/Hands-on Skills", "Trade-specific Techniques", "Tool Handling", "Safety Awareness", "Dexterity", "Physical Fitness"],
  specializations: ["Electrician", "Fitter", "Welder", "Machinist", "Diesel Mechanic", "Draughtsman (Civil/Mech)", "Electronics Mechanic", "Plumber", "Carpenter", "Refrigeration & AC"],
  certifications: ["NCVT (National Trade Certificate)", "SCVT (State)", "NAC (National Apprenticeship Certificate)", "NIMI online courses"],
  topRecruiters: ["Tata Motors", "Maruti Suzuki", "L&T", "Indian Railways", "Defence (Ordnance Factories)", "Power Plants", "Gulf/International (Middle East)"],
  workEnvironment: "Factory floor, workshop, construction site, or field service. Physical, hands-on work. May involve shifts. Gulf employment common for welders/electricians.",
  governmentJobs: ["Indian Railways (Technician)", "Defence (Ordnance, EME)", "PSUs (BHEL, NTPC, SAIL)", "State Electricity Boards", "Municipal Corporations"],
  privateJobs: ["Manufacturing Plants", "Automobile Service Centers", "Construction Companies", "Maintenance Services", "Gulf/Middle East Jobs"],
  researchOpportunities: ["Limited direct research — path upward is through Supervisor → Manager roles or self-employment", "CTI (Crafts Instructor Training) for teaching roles"],
  entrepreneurshipPotential: "Start auto repair garage, electrical shop, welding/fabrication unit, AC repair business, or plumbing service. ITI + experience = ideal entrepreneur",
  futureScope: ["Skill India / Make in India creating demand", "Gulf countries hiring skilled Indian workers", "Infrastructure projects needing tradesmen", "EV maintenance creating new trade specializations"],
  pros: ["Short training (6mo-2yr) — earn fast", "Minimal education cost", "Practical skills = always employed", "Gulf/International salary potential (₹50K-₹1L+/mo)", "Self-employment ready"],
  cons: ["Physically demanding work", "Lower domestic salary ceiling", "Limited white-collar transition", "Trade-dependent (some trades decline with tech)"],
  category: "ITI",
  timeToComplete: "6 months - 2 years",
  children: [
    leafNode("iti-electrician", "Electrician", "Wire, install, and maintain electrical systems",
      "One of the most versatile ITI trades. Course covers house wiring, industrial wiring, panel boards, motor winding, transformer maintenance, and safety. Electricians work in construction, manufacturing, power distribution, and domestic services. Government licensed electricians are always in demand.",
      "from-yellow-500 to-amber-600",
      { iconName: "Zap", educationPath: ["10th Pass", "ITI Electrician (1-2yr)", "Apprenticeship", "License (State Wireman)"],
        salaryRanges: { entry: "₹1.8L - ₹3L", mid: "₹3L - ₹6L", senior: "₹6L - ₹12L" }, growthOutlook: "High",
        skillsRequired: ["Wiring & Installation", "Circuit Knowledge", "Motor/Transformer", "Safety Protocols", "Troubleshooting"],
        topRecruiters: ["L&T", "Siemens", "Construction Companies", "Manufacturing Plants", "State Electricity Boards"],
        workEnvironment: "Construction sites, factories, or domestic service calls. May involve heights, confined spaces. Safety-critical.",
        governmentJobs: ["State Electricity Board (Lineman/Technician)", "Railways (Electrician)", "PSU Electrical Maintenance", "Municipal Corporations"], privateJobs: ["Electrical Contractors", "Manufacturing Plants", "Facility Management"],
        entrepreneurshipPotential: "Start electrical contracting firm — one of the most common ITI entrepreneur paths. License + experience → own business.",
        pros: ["Universal demand (every building needs electricity)", "Licensed trade = respected", "Self-employment friendly", "Gulf salary potential"], cons: ["Electrical hazards", "Physically demanding (crawling, heights)", "On-call for emergencies"],
        category: "ITI", timeToComplete: "1 - 2 years" }
    ),
    leafNode("iti-fitter", "Fitter", "Assemble, install, and maintain machinery with precision",
      "Fitter is one of the most fundamental ITI trades covering bench work, drilling, tapping, pipe fitting, alignment, and machine assembly. Fitters work in every manufacturing industry — from automobile plants to oil refineries. PSU recruitment (SAIL, BHEL, NTPC) regularly hires fitters through trade tests.",
      "from-slate-600 to-gray-500",
      { iconName: "Wrench", educationPath: ["10th Pass", "ITI Fitter (2yr)", "Apprenticeship", "Job / PSU recruitment"],
        salaryRanges: { entry: "₹2L - ₹3.5L", mid: "₹3.5L - ₹7L", senior: "₹7L - ₹12L" }, growthOutlook: "Stable",
        skillsRequired: ["Bench Work & Filing", "Drilling & Tapping", "Pipe Fitting", "Alignment", "Blueprint Reading"],
        topRecruiters: ["SAIL", "BHEL", "NTPC", "Indian Oil", "Tata Steel", "Automobile Plants"],
        workEnvironment: "Factory floor or assembly shop. Workshop environment. Team-based work on large machinery.",
        governmentJobs: ["PSU (SAIL, BHEL, NTPC, IOCL)", "Ordnance Factories", "Railways (Fitter)", "Defence (EME)"], privateJobs: ["Manufacturing", "Automobile", "Process Industries"],
        entrepreneurshipPotential: "Start fabrication shop, machine assembly service, or industrial maintenance business",
        pros: ["PSU job potential (stable, benefits)", "Broad industry applicability", "Foundation for supervisory roles"], cons: ["Manufacturing-dependent", "Physically demanding", "Lower pay than electrician/CS trades"],
        category: "ITI", timeToComplete: "2 years" }
    ),
    leafNode("iti-welder", "Welder", "Fuse metals — build ships, bridges, and pipelines",
      "Welding is a high-demand skilled trade covering arc welding, gas welding, TIG/MIG, and fabrication. Certified welders are in massive demand in construction, shipbuilding, oil & gas, and manufacturing. Gulf countries heavily recruit Indian welders with salaries of ₹50K-₹1L+/month. Advanced certifications (6G, underwater) can push earnings to ₹2L+/month.",
      "from-red-600 to-orange-500",
      { iconName: "Flame", educationPath: ["10th Pass", "ITI Welder (1yr)", "Advanced certs (TIG/MIG/6G)", "Gulf / Construction / Shipyard"],
        salaryRanges: { entry: "₹2L - ₹5L", mid: "₹5L - ₹10L", senior: "₹10L - ₹18L+" }, growthOutlook: "High",
        skillsRequired: ["Arc/Gas/TIG/MIG Welding", "Blueprint Reading", "Metal Knowledge", "Safety (Hot Work)", "Physical Stamina"],
        specializations: ["6G Welding (pipe)", "Underwater Welding", "TIG Welding (precision)", "Structural Welding"],
        topRecruiters: ["Shipyards (Cochin, Mazagon)", "L&T", "Oil & Gas (ONGC, Reliance)", "Construction", "Gulf Companies"],
        workEnvironment: "Shipyards, construction sites, pipelines, factory fabrication shops. Involves heat, noise, fumes — PPE essential. Gulf postings offer high pay but challenging conditions.",
        governmentJobs: ["Shipyards (Cochin, Garden Reach)", "Indian Railways", "PSU (ONGC, IOCL)", "Defence (Navy dockyards)"], privateJobs: ["Construction", "Shipbuilding", "Oil & Gas", "Gulf Employment"],
        entrepreneurshipPotential: "Start welding/fabrication shop — fabrication and structural steel work is lucrative",
        futureScope: ["Infrastructure construction boom", "Shipbuilding expansion", "Pipeline projects (gas/water)", "Underwater welding (niche, high-paying)"],
        pros: ["Gulf salary potential (₹50K-₹1L+/mo)", "Certifications boost pay significantly", "Always in demand (construction)", "Specialization (6G, underwater) is lucrative"], cons: ["Hot, physically demanding work", "Health risks (fumes, eye strain)", "Gulf deployments away from family", "Career length limited by physical health"],
        category: "ITI", timeToComplete: "1 - 2 years" }
    ),
    leafNode("iti-machinist", "Machinist / Turner", "Shape metal with precision — the foundation of manufacturing",
      "CNC (Computer Numerical Control) machining is the backbone of modern manufacturing. ITI Machinist or Turner covers lathe operations, CNC programming, and precision machining. With Make in India, precision machining skills are in high demand in automobile, aerospace, and defence manufacturing.",
      "from-blue-500 to-slate-500",
      { iconName: "Cog", educationPath: ["10th Pass", "ITI Machinist/Turner (2yr)", "CNC training", "Manufacturing / Aerospace"],
        salaryRanges: { entry: "₹2L - ₹4L", mid: "₹4L - ₹8L", senior: "₹8L - ₹15L" }, growthOutlook: "High",
        skillsRequired: ["Lathe/Milling Operations", "CNC Programming (G-code)", "Blueprint Reading", "Measurement (Micrometers)", "Precision Work"],
        topRecruiters: ["Tata Motors", "Mahindra", "Sundaram Clayton", "Bharat Forge", "Aerospace (HAL, NAL)"],
        workEnvironment: "Machine shop or CNC facility. Precision-focused, clean environment. CNC shops are air-conditioned. Shift work common.",
        governmentJobs: ["Ordnance Factories", "Railways (Workshop)", "HAL", "Defence Manufacturing"], privateJobs: ["Automobile Component", "Precision Engineering", "Aerospace", "Medical Devices"],
        entrepreneurshipPotential: "Start CNC job shop or precision machining unit — high capital but high-margin work",
        futureScope: ["Make in India manufacturing push", "Defence/Aerospace indigenization", "Medical device manufacturing", "Automation creating CNC demand"],
        pros: ["CNC skill is future-proof", "Aerospace/defence work is prestigious", "Clean work environment (modern CNC)", "Global demand for precision machinists"], cons: ["CNC machines are expensive (self-employment barrier)", "Repetitive work on production lines", "Shift work in manufacturing", "Physical (standing for hours)"],
        category: "ITI", timeToComplete: "2 years" }
    ),
    leafNode("iti-electronics", "Electronics Mechanic", "Repair and maintain electronic devices and systems",
      "ITI Electronics Mechanic covers electronic components, PCB assembly, testing, mobile/consumer electronics repair, and embedded basics. Electronics mechanics work in consumer electronics servicing, mobile repair, telecom equipment maintenance, and electronics manufacturing. Mobile repair shops are one of the most common small businesses started by this trade.",
      "from-violet-500 to-indigo-500",
      { iconName: "Smartphone", educationPath: ["10th Pass", "ITI Electronics Mechanic (2yr)", "Specialization (Mobile/IT)", "Job / Own shop"],
        salaryRanges: { entry: "₹1.8L - ₹3.5L", mid: "₹3.5L - ₹7L", senior: "₹7L - ₹12L" }, growthOutlook: "High",
        skillsRequired: ["Component Identification", "Soldering/Desoldering", "PCB Assembly", "Circuit Troubleshooting", "Mobile/Consumer Repair"],
        topRecruiters: ["Electronics Manufacturing (Foxconn, Dixon)", "Mobile Service Chains", "Telecom Companies", "Consumer Electronics Companies"],
        workEnvironment: "Repair shop, electronics factory, or field service. Clean, indoor. Mobile repair shops are independent small businesses.",
        governmentJobs: ["BSNL Technician", "Railways (S&T)", "Defence (Signals)", "ISRO Technical"], privateJobs: ["Electronics Manufacturing (EMS)", "Mobile Service Centers", "Telecom Field Maintenance"],
        entrepreneurshipPotential: "Start mobile repair shop — low investment, high demand. Or electronics servicing center.",
        futureScope: ["Mobile/consumer electronics explosion", "IoT device servicing emerging", "Refurbished electronics market growing", "Right to Repair movement"],
        pros: ["Low investment to start own business", "Mobile repair is recession-proof", "Clean indoor work", "Growing with electronics penetration"], cons: ["Rapid tech changes (continuous learning)", "Component-level repair is dying (modular)", "Manufacturing jobs repetitive"],
        category: "ITI", timeToComplete: "2 years" }
    ),
    leafNode("iti-diesel", "Diesel Mechanic / Motor Vehicle Mechanic", "Keep engines running — from trucks to earthmovers",
      "ITI Diesel Mechanic / MMV covers diesel engines, vehicle systems (brakes, transmission, electrical), diagnostics, and heavy vehicle maintenance. These mechanics are employed in transport companies, mining, construction equipment, and automobile service centers. Heavy vehicle (earthmover) mechanics are especially well-paid in mining and infrastructure.",
      "from-gray-600 to-slate-700",
      { iconName: "Truck", educationPath: ["10th Pass", "ITI Diesel Mechanic (1yr)", "Apprenticeship at dealership", "Job / Own garage"],
        salaryRanges: { entry: "₹1.8L - ₹3.5L", mid: "₹3.5L - ₹7L", senior: "₹7L - ₹15L" }, growthOutlook: "High",
        skillsRequired: ["Diesel Engine Systems", "Transmission & Brakes", "Vehicle Electronics", "Diagnostic Tools", "Hydraulics"],
        topRecruiters: ["Tata Motors (CV)", "Ashok Leyland", "Volvo Eicher", "Caterpillar", "Mining Companies", "Transport Fleets"],
        workEnvironment: "Garage/workshop, dealership service center, or mining/construction sites. Hands-on, greasy work. Heavy vehicle roles well-compensated.",
        governmentJobs: ["State Transport (Mechanic)", "Defence (EME)", "Mining PSUs (Coal India, NMDC)", "Municipal Transport"], privateJobs: ["Truck/Bus Fleets", "Construction Equipment", "Mining", "Dealerships"],
        entrepreneurshipPotential: "Start truck/bus repair garage or fleet maintenance service — good money in commercial vehicle repair",
        futureScope: ["Logistics/e-commerce driving truck demand", "Construction/mining equipment maintenance", "EV transition (retraining needed)", "Fleet management services"],
        pros: ["Heavy vehicle mechanics well-paid", "Always needed (transport never stops)", "Garage ownership is viable", "Mining roles offer high pay"], cons: ["Greasy, dirty work", "Heavy lifting, physically tough", "Mining postings in remote areas", "EV transition may reduce diesel demand"],
        category: "ITI", timeToComplete: "1 - 2 years" }
    ),
    leafNode("iti-draughtsman", "Draughtsman (Civil / Mechanical)", "Transform designs into technical blueprints",
      "ITI Draughtsman (Civil or Mechanical) covers CAD software (AutoCAD), technical drawing, 3D modeling, and blueprint preparation. Draughtsmen are the bridge between engineers and construction/manufacturing. With BIM (Building Information Modeling) and 3D tools, this has become a tech-enabled desk job rather than manual drafting.",
      "from-cyan-500 to-blue-500",
      { iconName: "DraftingCompass", educationPath: ["10th Pass", "ITI Draughtsman (2yr)", "AutoCAD/Revit proficiency", "Architecture/Engineering firm"],
        salaryRanges: { entry: "₹2L - ₹4L", mid: "₹4L - ₹8L", senior: "₹8L - ₹15L" }, growthOutlook: "High",
        skillsRequired: ["AutoCAD (2D/3D)", "Technical Drawing", "Revit/BIM (for Civil)", "SolidWorks (for Mech)", "Blueprint Reading"],
        topRecruiters: ["Architecture Firms", "Construction Companies", "Manufacturing (Design Dept)", "Real Estate Developers", "Engineering Consultancies"],
        workEnvironment: "Office/design studio. Desk job. Air-conditioned. Collaborative with architects and engineers.",
        governmentJobs: ["PWD (Draughtsman)", "CPWD", "Municipal Corporations", "Survey Departments", "Town Planning"], privateJobs: ["Architecture Firms", "Engineering Companies", "Real Estate", "Manufacturing (CAD)"],
        entrepreneurshipPotential: "Start freelance CAD design service or small design/drafting consultancy",
        futureScope: ["BIM adoption in construction", "3D printing design", "Smart city/GIS mapping", "Freelance CAD platforms (Upwork)"],
        pros: ["Office/desk job (no physical labor)", "Freelance potential (global CAD work)", "BIM specialization is lucrative", "Government draughtsman jobs available"], cons: ["Starting pay is low", "Repetitive work (redrawing)", "Need to keep up with software", "Limited career growth without degree"],
        category: "ITI", timeToComplete: "2 years" }
    ),
    leafNode("iti-refrigeration", "Refrigeration & Air Conditioning Mechanic", "Keep the world cool — HVAC specialist",
      "HVAC (Heating, Ventilation, AC) is one of the fastest-growing trades. ITI Refrigeration & AC Mechanic covers installation, repair, and maintenance of ACs, refrigerators, cold storage, and central air systems. With rising temperatures and AC penetration in India going from 8% to 50%+, this trade has massive growth potential.",
      "from-sky-400 to-blue-600",
      { iconName: "Thermometer", educationPath: ["10th Pass", "ITI R&AC (2yr)", "Company/dealership training", "Job / Own shop"],
        salaryRanges: { entry: "₹2L - ₹4L", mid: "₹4L - ₹8L", senior: "₹8L - ₹15L+" }, growthOutlook: "Very High",
        skillsRequired: ["Refrigeration Cycle", "AC Installation/Repair", "Electrical Troubleshooting", "Gas Handling", "Customer Service"],
        topRecruiters: ["Voltas", "Blue Star", "Daikin", "Hitachi", "LG", "Samsung", "Facility Management Companies"],
        workEnvironment: "Field service — travel to homes/offices for installation and repair. Outdoor work (AC outdoor units). Seasonal demand spikes (summer).",
        governmentJobs: ["Railway AC Maintenance", "Defence (EME AC)", "Government Buildings (CPWD)", "Hospital HVAC"], privateJobs: ["AC Companies (Installation/Service)", "Facility Management", "Cold Storage", "Mall/Hotel Maintenance"],
        entrepreneurshipPotential: "Start AC sales/service shop — steady year-round income with summer peaks. Franchise options from Voltas/Blue Star.",
        futureScope: ["AC penetration in India to grow 5x", "Cold chain infrastructure for food", "Data center cooling demand", "Green refrigerants transition"],
        pros: ["Massive growth (AC penetration surge)", "Seasonal work with high earnings in summer", "Self-employment friendly", "Data center cooling is niche, high-paying"], cons: ["Outdoor work in summer heat (ironic)", "Seasonal income variance", "Physically demanding (lifting units)", "Refrigerant gas handling needs safety"],
        category: "ITI", timeToComplete: "2 years" }
    ),
  ],
};
