import type { DecisionTreeNode } from "../decision-tree.types";
import { leafNode, TOP_MED_EXAMS, TOP_MED_COLLEGES, MED_SALARY } from "./shared";

// ═══════════════════════════════════════════════
// PCB BRANCH — Medical & Life Sciences
// ═══════════════════════════════════════════════

export const PCB_BRANCH: DecisionTreeNode = {
  id: "pcb",
  name: "PCB (Physics, Chemistry, Biology)",
  shortDescription: "Medical and life sciences track",
  detailedDescription: "PCB is the gateway to medical, dental, and life science careers. Students study Physics, Chemistry, and Biology with practical lab work. This track leads to MBBS, BDS, BAMS, BHMS, nursing, pharmacy, biotechnology, and many allied health careers. NEET-UG is the primary entrance exam for medical admissions.",
  iconName: "HeartPulse",
  color: "from-teal-500 to-emerald-500",
  educationPath: ["11th-12th with PCB", "Clear NEET-UG", "Pursue MBBS/BDS/BAMS/BHMS/B.Sc"],
  entranceExams: TOP_MED_EXAMS,
  topColleges: TOP_MED_COLLEGES,
  salaryRanges: MED_SALARY,
  growthOutlook: "Very High",
  skillsRequired: ["Biology Knowledge", "Memorization", "Empathy", "Diagnostic Thinking", "Lab Skills", "Patient Care"],
  specializations: ["MBBS", "BDS", "BAMS", "BHMS", "BPT", "B.Sc Nursing", "Pharmacy", "Biotechnology", "Agriculture", "Veterinary Science"],
  certifications: ["USMLE", "PLAB", "MRCP", "NEET-PG"],
  topRecruiters: ["Apollo Hospitals", "Fortis", "AIIMS", "Max Healthcare", "Sun Pharma", "Cipla", "Medanta"],
  workEnvironment: "Hospitals, clinics, labs, pharmaceutical companies, research institutions",
  governmentJobs: ["AIIMS Doctor", "ESIC Hospital", "Railways Medical", "State Health Services", "ICAR Scientist"],
  privateJobs: ["Hospital Doctor", "Private Practitioner", "Pharma Research", "Clinical Research"],
  researchOpportunities: ["ICMR", "CSIR", "Clinical trials", "Drug development", "Genetics research"],
  entrepreneurshipPotential: "Open your own clinic, diagnostic lab, or pharmacy",
  futureScope: ["Healthcare sector projected $372B by 2026", "Telemedicine growing rapidly", "Global demand for Indian doctors", "Biotech and pharma research expansion"],
  pros: ["Respected profession", "Job security", "Global opportunities", "Direct impact on human lives"],
  cons: ["Long education (5.5-10 years)", "High competition (NEET)", "Demanding work hours", "High responsibility"],
  category: "Science",
  timeToComplete: "5.5-8 years",
  children: [
    leafNode("pcb-mbbs", "MBBS (Medicine)", "Become a doctor — diagnose, treat, save lives",
      "MBBS is the primary medical degree in India (5.5 years including internship). Doctors diagnose, treat, and prevent illnesses. Specialization through MD/MS (3 years) opens paths to cardiology, neurology, surgery, and 20+ specializations. Super-specialization through DM/MCh (3 years) for advanced expertise.",
      "from-red-500 to-rose-500",
      { iconName: "Stethoscope", educationPath: ["12th PCB (50%+)", "Clear NEET-UG", "MBBS (4.5 + 1 year internship)", "MD/MS (3 years optional)", "DM/MCh (3 years optional)"],
        entranceExams: ["NEET-UG", "NEET-PG", "NEET-SS", "USMLE (US)", "PLAB (UK)"],
        topColleges: TOP_MED_COLLEGES, salaryRanges: MED_SALARY, growthOutlook: "Very High",
        skillsRequired: ["Medical Knowledge", "Diagnostic Skills", "Patient Communication", "Surgical Precision", "Empathy", "Stress Management"],
        specializations: ["Cardiology", "Neurology", "Orthopedics", "Pediatrics", "Oncology", "Psychiatry", "Radiology", "Dermatology", "ENT", "Ophthalmology"],
        certifications: ["MD/MS", "DM/MCh", "MRCP (UK)", "USMLE (US)"],
        topRecruiters: ["Apollo", "Fortis", "AIIMS", "Max", "Medanta", "NHS UK"],
        workEnvironment: "Hospitals, clinics, private practice. Long hours, high stress, deeply rewarding.",
        governmentJobs: ["AIIMS", "ESIC", "Railways Medical", "State Health", "UPSC CMS"],
        privateJobs: ["Corporate Hospitals", "Private Practice", "Telemedicine"],
        researchOpportunities: ["ICMR", "CSIR", "WHO", "Clinical trials"],
        entrepreneurshipPotential: "Open clinic, nursing home, or specialty hospital",
        futureScope: ["Healthcare growing 22% annually", "Telemedicine expanding", "Medical tourism booming", "AI-assisted diagnostics"],
        pros: ["Highest societal respect", "Lifetime job security", "Global career options", "Deep personal satisfaction"],
        cons: ["10-12 years to super-specialize", "Extremely competitive", "High stress, long hours", "Constant learning required"],
        category: "Science", timeToComplete: "5.5 - 12 years" }
    ),
    leafNode("pcb-bds", "BDS (Dental Surgery)", "Dental surgeon — oral health specialist",
      "BDS is a 5-year program (4+1 internship) for becoming a dental surgeon. Specialize in orthodontics, periodontics, endodontics, or oral surgery. With growing dental awareness and cosmetic dentistry boom in India, demand is rising steadily.",
      "from-sky-500 to-blue-500",
      { iconName: "Smile", educationPath: ["12th PCB (50%+)", "NEET-UG", "BDS (4+1 years)", "MDS (3 years optional)"],
        entranceExams: ["NEET-UG", "NEET MDS"], salaryRanges: { entry: "₹5L - ₹10L", mid: "₹12L - ₹25L", senior: "₹25L - ₹50L+" },
        growthOutlook: "High", topColleges: [{ name: "Maulana Azad Dental College", location: "Delhi", fees: "₹10K - ₹30K/yr" }, { name: "Govt Dental Mumbai", location: "Mumbai", fees: "₹20K - ₹50K/yr" }],
        skillsRequired: ["Manual Dexterity", "Patient Care", "Aesthetic Sense", "Diagnostic Skills"],
        specializations: ["Orthodontics", "Periodontics", "Endodontics", "Prosthodontics", "Oral Surgery"],
        topRecruiters: ["Clove Dental", "Apollo Dental", "Private Practice"],
        workEnvironment: "Dental clinic or hospital. Regular hours, good work-life balance.",
        governmentJobs: ["Dental Colleges", "ESIC", "Railways Dental"], privateJobs: ["Dental Chains", "Private Practice"],
        entrepreneurshipPotential: "Open dental clinic — most common and successful path",
        futureScope: ["Cosmetic dentistry booming", "Dental tourism growing", "Digital dentistry (3D printing)"],
        pros: ["Good work-life balance", "Own practice independence", "High demand"], cons: ["High clinic setup cost", "Lower ceiling vs MBBS", "Metro competition"],
        category: "Science", timeToComplete: "5-8 years" }
    ),
    leafNode("pcb-bams", "BAMS (Ayurvedic Medicine)", "Traditional Indian medicine with modern integration",
      "BAMS (5.5 years) integrates Ayurveda with modern medicine. With AYUSH ministry promotion, demand is growing. Practice in government AYUSH hospitals, open clinics, work in wellness centers, or pursue MD in Ayurveda.",
      "from-amber-500 to-yellow-500",
      { iconName: "Leaf", educationPath: ["12th PCB (50%+)", "NEET-UG", "BAMS (4.5+1 years)"],
        entranceExams: ["NEET-UG", "AIAPGET"], salaryRanges: { entry: "₹4L - ₹8L", mid: "₹8L - ₹18L", senior: "₹18L - ₹35L+" },
        growthOutlook: "High", topColleges: [{ name: "BHU Varanasi", location: "Varanasi", fees: "₹15K - ₹50K/yr" }, { name: "Gujarat Ayurved Univ", location: "Jamnagar", fees: "₹10K - ₹30K/yr" }],
        skillsRequired: ["Ayurvedic Knowledge", "Herbal Medicine", "Patient Care", "Wellness Counseling"],
        specializations: ["Kayachikitsa", "Shalya", "Panchakarma", "Rasashastra"],
        topRecruiters: ["Patanjali", "Dabur", "Himalaya", "AYUSH Hospitals"],
        workEnvironment: "AYUSH hospitals, wellness centers, private clinics, herbal industry",
        governmentJobs: ["AYUSH Hospitals", "Govt Ayurvedic Colleges", "CGHS"], privateJobs: ["Wellness Centers", "Private Practice", "Herbal Industry"],
        entrepreneurshipPotential: "Open Ayurvedic clinic, wellness center, or herbal product line",
        futureScope: ["Government AYUSH push", "Global wellness market $4.5T", "Medical tourism for Ayurveda"],
        pros: ["Less competition than MBBS", "Growing government support", "Holistic approach"], cons: ["Limited critical care", "Perception challenges", "Lower salary ceiling"],
        category: "Science", timeToComplete: "5.5-8 years" }
    ),
    leafNode("pcb-bhms", "BHMS (Homeopathic Medicine)", "Homeopathy — gentle and holistic healing",
      "BHMS (5.5 years) in homeopathy. Treat chronic conditions, allergies, and lifestyle disorders. With AYUSH ministry support and growing interest in alternative medicine, BHMS graduates have stable career options.",
      "from-lime-500 to-green-500",
      { iconName: "Pill", educationPath: ["12th PCB (50%+)", "NEET-UG", "BHMS (4.5+1 years)"],
        entranceExams: ["NEET-UG", "AIAPGET"], salaryRanges: { entry: "₹3L - ₹6L", mid: "₹6L - ₹15L", senior: "₹15L - ₹30L" },
        growthOutlook: "Moderate", topColleges: [{ name: "NIH Kolkata", location: "Kolkata", fees: "₹10K - ₹30K/yr" }, { name: "Nehru Homeopathic Delhi", location: "Delhi", fees: "₹10K - ₹30K/yr" }],
        skillsRequired: ["Homeopathic Principles", "Case Taking", "Materia Medica", "Patient Counseling"],
        topRecruiters: ["AYUSH Hospitals", "Homeopathic Clinics", "Wellness Centers"],
        workEnvironment: "Clinic or hospital OPD. Calm, unhurried patient interaction.",
        governmentJobs: ["AYUSH Hospitals", "CGHS"], privateJobs: ["Private Clinic", "Wellness Chains"],
        entrepreneurshipPotential: "Start independent homeopathic practice with low setup cost",
        futureScope: ["AYUSH integration in public health", "Lifestyle disease focus"],
        pros: ["Low stress", "Low investment to start", "Good for chronic care"], cons: ["Limited acute scope", "Scientific controversy", "Lower income"],
        category: "Science", timeToComplete: "5.5 years" }
    ),
    leafNode("pcb-bpt", "BPT (Physiotherapy)", "Restore movement, improve quality of life",
      "BPT (4.5 years) in physiotherapy. Help patients recover from injuries and surgeries through exercise and manual therapy. Growing demand with aging population and sports medicine boom (IPL, ISL teams hire physios).",
      "from-cyan-500 to-blue-500",
      { iconName: "Activity", educationPath: ["12th PCB (50%+)", "BPT (4 years + 6mo internship)", "MPT (2 years optional)"],
        entranceExams: ["State CETs", "IPU CET"], salaryRanges: { entry: "₹3L - ₹6L", mid: "₹6L - ₹15L", senior: "₹15L - ₹30L" },
        growthOutlook: "High", topColleges: [{ name: "CMC Vellore", location: "Vellore", fees: "₹20K - ₹50K/yr" }, { name: "IPH Delhi", location: "Delhi", fees: "₹15K - ₹40K/yr" }],
        skillsRequired: ["Anatomy", "Manual Therapy", "Exercise Prescription", "Biomechanics", "Patient Motivation"],
        specializations: ["Sports", "Neuro", "Pediatric", "Cardio-Respiratory", "Orthopedic"],
        topRecruiters: ["Apollo", "Fortis", "SAI", "IPL Teams", "Rehab Centers"],
        workEnvironment: "Hospital physio dept, sports clinics, rehab centers, private practice",
        governmentJobs: ["ESIC", "AIIMS", "SAI", "Defence"], privateJobs: ["Hospital Rehab", "Sports Teams", "Private Practice"],
        entrepreneurshipPotential: "Open physiotherapy clinic or rehab center",
        futureScope: ["Sports medicine growing", "Geriatric physio demand", "Tele-rehab emerging"],
        pros: ["Active, hands-on work", "Growing demand", "Good work-life balance"], cons: ["Physically demanding", "Lower starting pay", "Requires patience"],
        category: "Science", timeToComplete: "4.5 - 6.5 years" }
    ),
    leafNode("pcb-nursing", "B.Sc Nursing", "Care, comfort, and clinical excellence",
      "B.Sc Nursing (4 years) prepares registered nurses. Massive demand in India and globally — UK NHS, US hospitals, and Gulf countries actively recruit Indian nurses. INC registration required to practice.",
      "from-pink-500 to-rose-400",
      { iconName: "Heart", educationPath: ["12th PCB (45%+)", "B.Sc Nursing (4 years)", "INC Registration", "M.Sc (2 years optional)"],
        entranceExams: ["AIIMS Nursing", "State Nursing CETs"], salaryRanges: { entry: "₹3L - ₹5L", mid: "₹6L - ₹12L", senior: "₹15L - ₹25L" },
        growthOutlook: "Very High", topColleges: [{ name: "AIIMS Delhi Nursing", location: "Delhi", fees: "₹1K - ₹15K/yr" }, { name: "CMC Vellore Nursing", location: "Vellore", fees: "₹30K - ₹1L/yr" }],
        skillsRequired: ["Patient Care", "Clinical Procedures", "Empathy", "Communication", "Stress Management"],
        specializations: ["Critical Care", "Pediatric", "Psychiatric", "Community Health", "OT", "Oncology"],
        certifications: ["M.Sc Nursing", "IELTS/OET (abroad)", "NCLEX (US)", "NMC Registration (UK)"],
        topRecruiters: ["Apollo", "Fortis", "AIIMS", "NHS UK", "Dubai Health Authority"],
        workEnvironment: "Hospitals, ICUs, OTs. Shift work including nights and weekends.",
        governmentJobs: ["AIIMS", "ESIC", "CGHS", "Military Nursing"], privateJobs: ["Corporate Hospitals", "Nursing Homes", "Home Healthcare"],
        entrepreneurshipPotential: "Start home nursing service or elderly care facility",
        futureScope: ["Global nursing shortage", "Nurse practitioners expanding", "Specialized nursing growing"],
        pros: ["Global career options", "Job guarantee", "Respected", "Direct patient impact"], cons: ["Demanding shifts", "Emotional toll", "Night/weekend work"],
        category: "Science", timeToComplete: "4 - 6 years" }
    ),
    leafNode("pcb-pharmacy", "B.Pharm (Pharmacy)", "Expert in medicines — from lab to patient",
      "B.Pharm (4 years) leads to careers in pharma industry, hospital/retail pharmacy, and research. India is the 'pharmacy of the world' ($25B+ exports), creating massive demand across manufacturing, QC, and clinical roles.",
      "from-violet-500 to-purple-500",
      { iconName: "PillBottle", educationPath: ["12th PCB/PCM (50%+)", "B.Pharm (4 years)", "PCI Registration", "M.Pharm/Pharm.D optional"],
        entranceExams: ["State CETs", "GPAT", "NIPER JEE"], salaryRanges: { entry: "₹3L - ₹6L", mid: "₹6L - ₹15L", senior: "₹15L - ₹25L" },
        growthOutlook: "High", topColleges: [{ name: "NIPER Mohali", location: "Mohali", fees: "₹1L - ₹3L/yr" }, { name: "ICT Mumbai", location: "Mumbai", fees: "₹1L - ₹2L/yr" }],
        skillsRequired: ["Pharmacology", "Drug Interactions", "QC/QA", "Regulatory Knowledge", "Patient Counseling"],
        specializations: ["Pharmaceutics", "Pharmacology", "Pharm Chemistry", "Clinical Pharmacy", "Regulatory Affairs"],
        topRecruiters: ["Sun Pharma", "Cipla", "Dr. Reddy", "Apollo Pharmacy", "MedPlus"],
        workEnvironment: "Pharma manufacturing, R&D labs, hospital/retail pharmacy. Clean, regulated.",
        governmentJobs: ["Drug Inspector", "Government Hospitals", "CDSCO"], privateJobs: ["Pharma Companies", "Retail Chains", "CROs"],
        entrepreneurshipPotential: "Open medical store or pharma distribution business",
        futureScope: ["Pharma exports growing 15%", "Biologics booming", "Clinical research expanding"],
        pros: ["Stable industry", "Multiple paths", "Can open own business"], cons: ["Modest starting salary", "High responsibility", "R&D competitive"],
        category: "Science", timeToComplete: "4 - 6 years" }
    ),
    leafNode("pcb-biotech", "Biotechnology", "Harness biology to solve global challenges",
      "B.Tech/B.Sc Biotech combines biology with technology for healthcare, agriculture, and environment. From vaccine development to GM crops, biotech is at the frontier. India biotech sector projected $150B by 2030.",
      "from-emerald-500 to-green-500",
      { iconName: "Microscope", educationPath: ["12th PCB/PCMB (60%+)", "B.Tech/B.Sc Biotech (3-4yr)", "M.Tech/M.Sc (2yr)", "Ph.D for research"],
        entranceExams: ["JEE Main", "CUET", "GATE Biotech"], salaryRanges: { entry: "₹3.5L - ₹7L", mid: "₹8L - ₹18L", senior: "₹18L - ₹35L" },
        growthOutlook: "Very High", topColleges: [{ name: "IIT Kharagpur", location: "Kharagpur", fees: "₹2L - ₹8L/yr" }, { name: "VIT Vellore", location: "Vellore", fees: "₹3L - ₹12L/yr" }],
        skillsRequired: ["Molecular Biology", "Genetic Engineering", "Bioprocess", "Bioinformatics", "Lab Safety"],
        specializations: ["Genetic Engineering", "Bioinformatics", "Industrial Biotech", "Medical Biotech", "Agri Biotech", "Environmental Biotech"],
        certifications: ["CSIR-NET", "GATE Biotech", "DBT-BET"],
        topRecruiters: ["Biocon", "Serum Institute", "Bharat Biotech", "Syngene", "Novozymes"],
        workEnvironment: "Research labs, pharma companies, agri-tech firms. Controlled, clean.",
        governmentJobs: ["DBT Labs", "ICAR", "CSIR", "DRDO"], privateJobs: ["Pharma Biotech", "Agri Biotech", "Bio-IT"],
        researchOpportunities: ["Genomics", "CRISPR research", "Vaccine development", "Enzyme engineering"],
        entrepreneurshipPotential: "Start biotech venture in agri/healthcare/industrial enzymes",
        futureScope: ["mRNA vaccine revolution", "CRISPR gene editing", "Biofuels and green tech", "Personalized medicine"],
        pros: ["Cutting-edge field", "Solving real problems", "Growing investment"], cons: ["Ph.D for top research", "Lab work repetitive", "Indian industry maturing"],
        category: "Science", timeToComplete: "4 - 8 years" }
    ),
    leafNode("pcb-agriculture", "B.Sc Agriculture", "Feed the nation — modern agri-science",
      "B.Sc Agriculture (4 years) covers crop science, soil science, animal husbandry, and agri-economics. With agri-tech booming and India being agrarian, agriculture graduates are in demand in banking, agri-business, government, and research.",
      "from-lime-600 to-yellow-600",
      { iconName: "Sprout", educationPath: ["12th PCB/PCM (50%+)", "B.Sc Agriculture (4yr)", "M.Sc (2yr optional)", "Ph.D for research"],
        entranceExams: ["ICAR AIEEA", "State Agriculture CETs"], salaryRanges: { entry: "₹3L - ₹6L", mid: "₹6L - ₹15L", senior: "₹15L - ₹30L" },
        growthOutlook: "High", topColleges: [{ name: "IARI Delhi", location: "Delhi", fees: "₹20K - ₹50K/yr" }, { name: "GBPUAT Pantnagar", location: "Pantnagar", fees: "₹30K - ₹80K/yr" }],
        skillsRequired: ["Crop Science", "Soil Management", "Agri-business", "Farm Economics", "Sustainable Practices"],
        specializations: ["Agronomy", "Horticulture", "Plant Breeding", "Soil Science", "Agri Economics", "Entomology"],
        topRecruiters: ["Godrej Agrovet", "Mahyco", "ITC Agri", "NABARD", "IFFCO"],
        workEnvironment: "Mix of field work and office. Farms, research stations, agri-business operations.",
        governmentJobs: ["ICAR Scientist", "Agriculture Officer", "NABARD", "FCI", "State Agri Dept"],
        privateJobs: ["Agri-Input Companies", "Food Processing", "Agri-Tech Startups"],
        entrepreneurshipPotential: "Start organic farming, agri-tech startup, or food processing unit",
        futureScope: ["Agri-tech startups booming", "Organic farming demand surging", "Climate-resilient agriculture"],
        pros: ["Diverse options", "Government jobs", "Agri-tech revolution"], cons: ["Field work tough", "Lower starting salaries", "Weather-dependent"],
        category: "Science", timeToComplete: "4 - 6 years" }
    ),
    leafNode("pcb-veterinary", "Veterinary Science (B.V.Sc & AH)", "Care for animals and ensure food safety",
      "B.V.Sc & AH (5.5 years) for becoming a veterinary doctor. Treat animals, ensure livestock health, inspect food products, and contribute to public health. Growing pet ownership and livestock industry create expanding opportunities.",
      "from-orange-500 to-amber-500",
      { iconName: "PawPrint", educationPath: ["12th PCB (50%+)", "NEET-UG or AIPVT", "B.V.Sc & AH (5.5yr)", "M.V.Sc (2yr optional)"],
        entranceExams: ["NEET-UG", "AIPVT"], salaryRanges: { entry: "₹3.5L - ₹7L", mid: "₹7L - ₹18L", senior: "₹18L - ₹35L" },
        growthOutlook: "High", topColleges: [{ name: "IVRI Bareilly", location: "Bareilly", fees: "₹15K - ₹40K/yr" }, { name: "GADVASU Ludhiana", location: "Ludhiana", fees: "₹30K - ₹80K/yr" }],
        skillsRequired: ["Animal Handling", "Surgical Skills", "Diagnostic Ability", "Public Health", "Zoonosis Understanding"],
        specializations: ["Surgery", "Animal Nutrition", "Poultry Science", "Livestock", "Wildlife Medicine"],
        topRecruiters: ["State Animal Husbandry", "Amul", "Venky", "NGOs (Wildlife)"],
        workEnvironment: "Vet hospitals, farms, wildlife sanctuaries. Physically demanding at times.",
        governmentJobs: ["State Animal Husbandry", "Military Farms", "ICAR", "FSSAI", "Wildlife (Customs)"],
        privateJobs: ["Private Vet Practice", "Dairy/Poultry Industry", "Pharma (Animal Health)"],
        entrepreneurshipPotential: "Open veterinary clinic, pet care center, or livestock consultancy",
        futureScope: ["Pet industry booming in cities", "Dairy/poultry growing", "Wildlife conservation expanding", "One Health approach"],
        pros: ["Growing pet sector", "Government jobs", "Animal welfare satisfaction"], cons: ["Physically demanding", "Zoonosis risk", "Rural postings"],
        category: "Science", timeToComplete: "5.5 - 7.5 years" }
    ),
    leafNode("pcb-food-tech", "Food Technology", "Safe, nutritious, innovative food products",
      "Food Technology applies science to food processing, preservation, packaging, and quality. With India food processing industry booming and FSSAI regulation expanding, food technologists are in growing demand.",
      "from-orange-400 to-red-400",
      { iconName: "UtensilsCrossed", educationPath: ["12th PCB/PCM (50%+)", "B.Tech/B.Sc Food Tech (3-4yr)", "M.Tech/M.Sc (2yr optional)"],
        entranceExams: ["JEE Main", "ICAR AIEEA", "State CETs"], salaryRanges: { entry: "₹3L - ₹6L", mid: "₹6L - ₹15L", senior: "₹15L - ₹25L" },
        growthOutlook: "High", topColleges: [{ name: "CFTRI Mysore", location: "Mysore", fees: "₹30K - ₹80K/yr" }, { name: "NIFTEM Kundli", location: "Sonipat", fees: "₹1L - ₹2L/yr" }],
        skillsRequired: ["Food Chemistry", "QC/QA", "HACCP", "Sensory Analysis", "Food Safety"],
        specializations: ["Food Processing", "Quality Assurance", "Food Microbiology", "Nutraceuticals", "Food Packaging"],
        certifications: ["HACCP", "ISO 22000", "FSSAI FoSTaC"],
        topRecruiters: ["Nestle", "Britannia", "ITC Foods", "Amul", "PepsiCo", "FSSAI"],
        workEnvironment: "Food processing plants, quality labs, R&D centers. Shift work in production.",
        governmentJobs: ["FSSAI", "BIS", "CFTRI", "APEDA"], privateJobs: ["Food Companies", "Beverage", "Dairy", "QSR"],
        entrepreneurshipPotential: "Start food processing unit, artisanal food brand, or food testing lab",
        futureScope: ["Ready-to-eat market booming", "Nutraceuticals growing", "Food safety regulation expanding", "Plant-based protein revolution"],
        pros: ["Recession-proof industry", "Diverse products", "Creative + scientific"], cons: ["Moderate starting salaries", "Shift work in production"],
        category: "Science", timeToComplete: "4 - 6 years" }
    ),
    leafNode("pcb-microbiology", "Microbiology", "Study microorganisms for health and industry",
      "B.Sc/M.Sc Microbiology leads to careers in pharma QC, clinical microbiology, food safety, and research. Microbiologists work in hospitals, pharma companies, research labs, and regulatory bodies. Growing field with biotech expansion.",
      "from-green-500 to-teal-500",
      { iconName: "Scan", educationPath: ["12th PCB", "B.Sc Microbiology (3yr)", "M.Sc (2yr)", "Ph.D optional"],
        salaryRanges: { entry: "₹3L - ₹5L", mid: "₹5L - ₹12L", senior: "₹12L - ₹25L" }, growthOutlook: "High",
        topRecruiters: ["Sun Pharma", "SRL Diagnostics", "Nestle", "Water Testing Labs"],
        skillsRequired: ["Microbiological Techniques", "Sterile Technique", "Biochemical Testing", "Lab Safety"],
        specializations: ["Medical Microbiology", "Industrial Microbiology", "Food Microbiology", "Environmental Microbiology"],
        category: "Science", timeToComplete: "5 - 8 years" }
    ),
    leafNode("pcb-genetics", "Genetics", "Decode DNA to advance healthcare and agriculture",
      "B.Sc/M.Sc Genetics leads to careers in genetic counseling, clinical genetics, forensics, and research. The genomics revolution is creating new opportunities in personalized medicine and agricultural biotechnology. India genomics market is growing rapidly.",
      "from-purple-500 to-indigo-500",
      { iconName: "Dna", educationPath: ["12th PCB", "B.Sc Genetics (3yr)", "M.Sc (2yr)", "Ph.D for research"],
        salaryRanges: { entry: "₹3.5L - ₹7L", mid: "₹7L - ₹15L", senior: "₹15L - ₹30L" }, growthOutlook: "Very High",
        topRecruiters: ["MedGenome", "Strand Life Sciences", "MapMyGenome", "ICMR"],
        skillsRequired: ["Molecular Biology", "Genomics", "Bioinformatics", "Statistical Genetics", "Lab Techniques"],
        specializations: ["Clinical Genetics", "Molecular Genetics", "Population Genetics", "Cancer Genetics"],
        category: "Science", timeToComplete: "5 - 8 years" }
    ),
    leafNode("pcb-biomedical", "Biomedical Science", "Bridge medicine and engineering",
      "B.Sc/B.Tech Biomedical Science applies engineering principles to healthcare — designing medical devices, prosthetics, and diagnostic equipment. Growing field with opportunities in med-tech companies and hospitals. India medical devices market to reach $50B by 2030.",
      "from-blue-500 to-indigo-500",
      { iconName: "CircuitBoard", educationPath: ["12th PCB/PCM", "B.Sc/B.Tech Biomedical (3-4yr)", "M.Tech (2yr optional)"],
        salaryRanges: { entry: "₹4L - ₹8L", mid: "₹8L - ₹18L", senior: "₹18L - ₹35L" }, growthOutlook: "Very High",
        topRecruiters: ["Siemens Healthineers", "GE Healthcare", "Philips", "Medtronic"],
        skillsRequired: ["Biomedical Engineering", "Medical Device Design", "Physiology", "Signal Processing", "Regulatory Affairs"],
        specializations: ["Medical Devices", "Biomaterials", "Rehabilitation Engineering", "Clinical Engineering"],
        category: "Science", timeToComplete: "4 - 6 years" }
    ),
    leafNode("pcb-allied-health", "Allied Health Sciences", "Essential healthcare support professions",
      "Includes B.Sc in Medical Lab Technology, Radiology, Operation Theatre Technology, Cardiac Care, Dialysis, etc. These 3-4 year programs lead to stable hospital careers with growing demand as healthcare infrastructure expands across India.",
      "from-sky-400 to-cyan-500",
      { iconName: "Activity", educationPath: ["12th PCB", "B.Sc Allied Health (3-4yr)", "M.Sc optional"],
        salaryRanges: { entry: "₹3L - ₹5L", mid: "₹5L - ₹12L", senior: "₹12L - ₹20L" }, growthOutlook: "High",
        topRecruiters: ["Apollo", "Fortis", "SRL Diagnostics", "Metropolis"],
        skillsRequired: ["Clinical Techniques", "Equipment Operation", "Patient Care", "Documentation"],
        specializations: ["MLT", "Radiology", "OT Technology", "Cardiac Technology", "Dialysis", "Respiratory Therapy"],
        category: "Science", timeToComplete: "3 - 5 years" }
    ),
    leafNode("pcb-environmental", "Environmental Science", "Protect the planet — sustainability and conservation",
      "B.Sc/M.Sc Environmental Science addresses climate change, pollution control, waste management, and conservation. Growing field with opportunities in government, NGOs, corporate sustainability, and environmental consulting. India has ambitious climate goals creating new jobs.",
      "from-green-600 to-emerald-500",
      { iconName: "Leaf", educationPath: ["12th PCB/PCM", "B.Sc Env Science (3yr)", "M.Sc (2yr)", "Ph.D for research"],
        salaryRanges: { entry: "₹3L - ₹6L", mid: "₹6L - ₹15L", senior: "₹15L - ₹25L" }, growthOutlook: "Very High",
        certifications: ["LEED", "NEBOSH", "ISO 14001"],
        topRecruiters: ["TERI", "CPCB", "UNDP", "Environmental Consultancies"],
        skillsRequired: ["Ecology", "Environmental Law", "Impact Assessment", "GIS", "Data Analysis"],
        specializations: ["Climate Change", "Waste Management", "Water Resources", "Renewable Energy", "Conservation Biology"],
        governmentJobs: ["MoEFCC", "CPCB", "State Pollution Boards", "Forest Dept"], privateJobs: ["ESG Consulting", "Renewable Energy", "Waste Management"],
        category: "Science", timeToComplete: "5 - 7 years" }
    ),
  ],
};
