import type { DecisionTreeNode } from "../decision-tree.types";
import { leafNode, TOP_ENGG_EXAMS, TOP_ENGG_COLLEGES, ENGG_SALARY } from "./shared";

// ═══════════════════════════════════════════════
// PCM BRANCH — Engineering & Technology
// ═══════════════════════════════════════════════

export const PCM_BRANCH: DecisionTreeNode = {
  id: "pcm",
  name: "PCM (Physics, Chemistry, Mathematics)",
  shortDescription: "Engineering, technology, and mathematics track",
  detailedDescription: "PCM is the most popular path to engineering. Students study Physics, Chemistry, and Mathematics. This opens all engineering branches (CS, Mechanical, Civil, Electrical, etc.), architecture, data science, and pure sciences. JEE Main/Advanced are the primary entrance exams. India produces 1.5M+ engineers annually.",
  iconName: "Cpu",
  color: "from-blue-500 to-indigo-500",
  educationPath: ["11th-12th with PCM (60%+ marks)", "JEE Main/BITSAT/State CET", "B.Tech/B.E. (4 years)", "M.Tech/MBA (optional)"],
  entranceExams: TOP_ENGG_EXAMS,
  topColleges: TOP_ENGG_COLLEGES,
  salaryRanges: ENGG_SALARY,
  growthOutlook: "Very High",
  skillsRequired: ["Mathematics", "Physics", "Programming", "Problem Solving", "Analytical Thinking", "Technical Design"],
  specializations: ["CS Engineering", "Mechanical", "Civil", "Electrical", "Electronics", "Chemical", "Aerospace", "AI & ML"],
  certifications: ["GATE", "GRE", "PE (Professional Engineer)", "AWS/Azure/Cloud certs"],
  topRecruiters: ["Google", "Microsoft", "Amazon", "L&T", "ISRO", "DRDO", "Tata Motors", "BHEL"],
  workEnvironment: "Offices, labs, construction sites, manufacturing plants depending on branch",
  governmentJobs: ["ISRO", "DRDO", "BARC", "PSUs via GATE", "IES", "Railways", "CPWD"],
  privateJobs: ["Software Engineer", "Data Scientist", "Product Designer", "Consultant", "Core Engineering"],
  researchOpportunities: ["IISc", "IITs", "CSIR Labs", "International PhD programs"],
  entrepreneurshipPotential: "Very high — tech startups, engineering consultancy, manufacturing ventures",
  futureScope: ["AI/ML creating unprecedented tech demand", "EV revolution for mechanical/electrical", "Space tech privatization (ISRO/private)", "Industry 4.0 and robotics automation"],
  pros: ["Highest paying tech careers", "Global demand for engineers", "Diverse branches", "Strong alumni networks"],
  cons: ["Extremely competitive exams", "Academic pressure", "Constant upskilling needed", "Core branches need passion"],
  category: "Science",
  timeToComplete: "4-6 years",
  children: [
    leafNode("pcm-cs", "Computer Science Engineering", "Build the digital world — software, AI, systems",
      "CSE is the most sought-after branch. Study programming, algorithms, AI/ML, databases, networks, and software engineering. India IT industry employs 5M+ professionals. Top grads get ₹20L-₹1Cr+ offers from FAANG and product companies. Remote-friendly, high-growth field.",
      "from-brand-royal to-brand-electric",
      { iconName: "Code", educationPath: ["12th PCM (60%+)", "JEE/BITSAT", "B.Tech CSE (4yr)", "M.Tech/MS (optional)"],
        entranceExams: TOP_ENGG_EXAMS, salaryRanges: { entry: "₹8L - ₹20L", mid: "₹20L - ₹50L", senior: "₹50L - ₹1.5Cr+" }, growthOutlook: "Very High",
        topColleges: TOP_ENGG_COLLEGES,
        skillsRequired: ["Programming (Python/Java/C++)", "DSA", "System Design", "Databases", "AI/ML", "Problem Solving"],
        specializations: ["AI & ML", "Cybersecurity", "Cloud Computing", "Blockchain", "Full Stack", "DevOps", "AR/VR"],
        certifications: ["AWS Solutions Architect", "Google Cloud ML", "CISSP (Security)", "Kubernetes"],
        topRecruiters: ["Google", "Microsoft", "Amazon", "Atlassian", "Flipkart", "Uber", "CRED", "PhonePe"],
        workEnvironment: "Modern offices, highly remote-friendly. Collaborative, fast-paced, great perks.",
        governmentJobs: ["ISRO", "DRDO", "NIC", "C-DAC", "PSU IT roles"], privateJobs: ["FAANG", "Startups", "IT Services", "Product"],
        researchOpportunities: ["AI Research Labs", "PhD at IITs/IISc", "Quantum Computing", "HCI"],
        entrepreneurshipPotential: "Start your own tech startup — India has 100+ unicorns and counting",
        futureScope: ["Generative AI revolution", "Quantum computing emerging", "Web3/blockchain growth", "Cybersecurity demand surging"],
        pros: ["Highest salaries in engineering", "Remote work options", "Global opportunities", "Fast career growth"],
        cons: ["Constant learning needed", "High competition for top roles", "Screen time heavy", "Rapid tech obsolescence"],
        category: "Science", timeToComplete: "4 - 6 years" }
    ),
    leafNode("pcm-mechanical", "Mechanical Engineering", "Design and build the machines that power the world",
      "One of engineering's broadest disciplines. Study thermodynamics, fluid mechanics, manufacturing, CAD/CAM, and robotics. Work in automotive, aerospace, energy, and manufacturing. The EV revolution and Industry 4.0 are creating renewed demand for mechanical engineers.",
      "from-gray-600 to-gray-400",
      { iconName: "Cog", educationPath: ["12th PCM (55%+)", "JEE/BITSAT", "B.Tech ME (4yr)", "GATE for PSUs / M.Tech"],
        entranceExams: TOP_ENGG_EXAMS, salaryRanges: { entry: "₹3.5L - ₹8L", mid: "₹8L - ₹18L", senior: "₹18L - ₹35L" }, growthOutlook: "High",
        topColleges: [{ name: "IIT Madras", location: "Chennai", fees: "₹2L - ₹8L/yr" }, { name: "IIT Delhi", location: "Delhi", fees: "₹2L - ₹8L/yr" }],
        skillsRequired: ["CAD/CAM (SolidWorks/AutoCAD)", "Thermodynamics", "Fluid Mechanics", "MATLAB/ANSYS", "Manufacturing Processes", "Project Management"],
        specializations: ["Automotive", "Thermal Engineering", "Manufacturing", "Robotics", "Aerospace", "HVAC", "Mechatronics"],
        certifications: ["GATE", "ASME Certification", "Six Sigma Green Belt", "CSWP (SolidWorks)"],
        topRecruiters: ["Tata Motors", "Mahindra", "L&T", "BHEL", "ONGC", "GE", "Siemens", "Bosch", "ISRO"],
        workEnvironment: "Mix of office design work and plant/factory visits. Manufacturing roles are more hands-on.",
        governmentJobs: ["BHEL", "ONGC", "GAIL", "ISRO", "DRDO", "Indian Railways", "NTPC", "HAL"],
        privateJobs: ["Automotive Companies", "Manufacturing", "Aerospace", "Consulting", "Product Design"],
        researchOpportunities: ["IIT Research Labs", "CSIR-CMERI", "DRDO Labs", "Space Research"],
        entrepreneurshipPotential: "Start manufacturing unit, auto service center, or product design firm",
        futureScope: ["EV revolution transforming automotive", "Industry 4.0 smart manufacturing", "Robotics and automation growth", "3D printing/additive manufacturing"],
        pros: ["Broadest engineering field", "Tangible, hands-on work", "PSU job opportunities", "Evergreen demand"], cons: ["Lower starting pay vs CS", "Plant work can be tough", "Needs passion and patience"],
        category: "Science", timeToComplete: "4 - 6 years" }
    ),
    leafNode("pcm-civil", "Civil Engineering", "Build the infrastructure that shapes civilization",
      "Civil engineers design and construct buildings, bridges, roads, dams, metro rails, and water systems. With India's $1.4 trillion infrastructure pipeline (NIP), smart cities mission, and bullet train projects, civil engineers are in massive demand across public and private sectors.",
      "from-amber-600 to-yellow-500",
      { iconName: "Building2", educationPath: ["12th PCM (55%+)", "JEE/BITSAT", "B.Tech CE (4yr)", "GATE/IES for govt jobs"],
        entranceExams: TOP_ENGG_EXAMS, salaryRanges: { entry: "₹3L - ₹7L", mid: "₹7L - ₹15L", senior: "₹15L - ₹30L" }, growthOutlook: "High",
        topColleges: [{ name: "IIT Bombay", location: "Mumbai", fees: "₹2L - ₹8L/yr" }, { name: "IIT Roorkee", location: "Roorkee", fees: "₹2L - ₹8L/yr" }, { name: "NIT Surathkal", location: "Mangalore", fees: "₹1.5L - ₹5L/yr" }],
        skillsRequired: ["Structural Analysis", "AutoCAD/STAAD Pro", "Construction Management", "Surveying", "Quantity Estimation", "Geotechnical Engineering"],
        specializations: ["Structural Engineering", "Geotechnical", "Transportation", "Environmental", "Water Resources", "Construction Management"],
        certifications: ["GATE", "IES/ESE", "PMI-PMP", "LEED AP", "Primavera"],
        topRecruiters: ["L&T", "DLF", "Tata Projects", "Shapoorji Pallonji", "NHAI", "Indian Railways", "CPWD"],
        workEnvironment: "Mix of office design and construction site work. Travel to project locations common. Site roles more physically demanding.",
        governmentJobs: ["NHAI", "CPWD", "PWD", "Indian Railways", "Municipal Corporations", "Metro Rail", "PSUs via GATE"],
        privateJobs: ["Construction", "Real Estate", "Infrastructure", "Consulting Firms", "Project Management"],
        researchOpportunities: ["IITs", "CBRI Roorkee", "SERC Chennai", "CRRI"],
        entrepreneurshipPotential: "Start construction firm, real estate development, or project consultancy. Numerous government tenders.",
        futureScope: ["$1.4T infrastructure pipeline", "100+ Smart Cities mission", "Bullet train and metro expansion", "Green building and sustainability"],
        pros: ["Infrastructure boom job security", "Government job options", "Own business potential", "Tangible impact"], cons: ["Site work in remote areas", "Weather-dependent", "Longer career growth curve"],
        category: "Science", timeToComplete: "4 - 6 years" }
    ),
    leafNode("pcm-electrical", "Electrical Engineering", "Power the world — generation to distribution",
      "Electrical engineers design and maintain power systems, motors, and electronics. With renewable energy transition (solar/wind), EV revolution, and smart grid projects, electrical engineers are critical to India's energy future. PSUs like NTPC, Power Grid, BHEL offer excellent government jobs via GATE.",
      "from-yellow-400 to-orange-500",
      { iconName: "Zap", educationPath: ["12th PCM (55%+)", "JEE/BITSAT", "B.Tech EE (4yr)", "GATE for PSUs"],
        entranceExams: TOP_ENGG_EXAMS, salaryRanges: { entry: "₹3.5L - ₹7L", mid: "₹7L - ₹18L", senior: "₹18L - ₹35L" }, growthOutlook: "High",
        topColleges: [{ name: "IIT Bombay", location: "Mumbai", fees: "₹2L - ₹8L/yr" }, { name: "IIT Kanpur", location: "Kanpur", fees: "₹2L - ₹8L/yr" }],
        skillsRequired: ["Circuit Analysis", "Power Systems", "Control Systems", "MATLAB/Simulink", "PCB Design", "Renewable Energy Tech"],
        specializations: ["Power Systems", "Renewable Energy", "Control Systems", "Power Electronics", "Electric Vehicles", "Smart Grid"],
        certifications: ["GATE", "IEEE Membership", "Solar PV Certification", "Energy Auditor"],
        topRecruiters: ["BHEL", "NTPC", "Power Grid", "Siemens", "ABB", "Tata Power", "Schneider Electric", "Adani Power"],
        workEnvironment: "Power plants, substations, manufacturing facilities, offices. Field visits and shift work in generation.",
        governmentJobs: ["NTPC", "Power Grid", "BHEL", "State Electricity Boards", "PGCIL", "NHPC", "PSUs via GATE"],
        privateJobs: ["Power Industry", "Manufacturing", "EV Industry", "Renewable Energy", "Consulting"],
        researchOpportunities: ["IITs", "CPRI", "Solar Energy Centre", "Smart Grid Pilots"],
        entrepreneurshipPotential: "Start solar installation business, electrical contracting, or EV charging network",
        futureScope: ["500GW renewable target by 2030", "EV charging infrastructure boom", "Smart grid deployment", "Battery storage revolution"],
        pros: ["PSU jobs with great benefits", "Critical infrastructure role", "Renewable energy boom", "EV industry growth"], cons: ["Field work in plants", "Shift duties sometimes", "Safety risks with high voltage"],
        category: "Science", timeToComplete: "4 - 6 years" }
    ),
    leafNode("pcm-electronics", "Electronics & Communication Engg", "Design chips and networks connecting the world",
      "ECE covers electronic circuits, embedded systems, VLSI design, communication networks, and IoT. With India's semiconductor push ($10B incentive), 5G rollout, and IoT revolution, ECE engineers are in high demand across telecom, chip design, and consumer electronics.",
      "from-cyan-500 to-blue-600",
      { iconName: "Radio", educationPath: ["12th PCM (60%+)", "JEE/BITSAT", "B.Tech ECE (4yr)", "M.Tech VLSI/Embedded (optional)"],
        entranceExams: TOP_ENGG_EXAMS, salaryRanges: { entry: "₹4L - ₹10L", mid: "₹10L - ₹25L", senior: "₹25L - ₹50L+" }, growthOutlook: "Very High",
        topColleges: TOP_ENGG_COLLEGES,
        skillsRequired: ["Digital Electronics", "VLSI Design", "Embedded Systems", "Signal Processing", "Verilog/VHDL", "IoT Protocols"],
        specializations: ["VLSI Design", "Embedded Systems", "5G/6G Communication", "IoT", "Signal Processing", "Robotics"],
        certifications: ["ARM Certified", "FPGA Design", "Cisco CCNA/CCNP", "Cadence Tools"],
        topRecruiters: ["Qualcomm", "Intel", "Samsung", "Texas Instruments", "Nokia", "Ericsson", "ISRO", "Bharat Electronics"],
        workEnvironment: "Labs and design offices. Circuit design, testing, and simulation. Clean, indoor environment.",
        governmentJobs: ["ISRO", "DRDO", "BEL", "HAL", "ECIL", "Bharat Electronics Ltd"],
        privateJobs: ["Semiconductor", "Telecom", "Consumer Electronics", "Automotive Electronics"],
        researchOpportunities: ["IITs VLSI Labs", "SAMEER", "SCL Chandigarh", "C-DAC"],
        entrepreneurshipPotential: "Start IoT startup, electronics manufacturing, or embedded design services",
        futureScope: ["India semiconductor mission ($10B+)", "5G/6G rollout", "IoT devices explosion", "Chip design boom"],
        pros: ["Semiconductor boom opportunities", "Blend of hardware + software", "R&D-oriented", "Defence sector jobs"], cons: ["Highly specialized", "Rapid tech change", "Chip design needs advanced degree"],
        category: "Science", timeToComplete: "4 - 6 years" }
    ),
    leafNode("pcm-chemical", "Chemical Engineering", "Transform raw materials into valuable products",
      "Chemical engineers design processes for manufacturing chemicals, pharmaceuticals, fuels, food, and materials. With India's process industry growing (pharma, petrochemicals, FMCG), chemical engineers have diverse careers in manufacturing, R&D, and process safety.",
      "from-green-500 to-teal-600",
      { iconName: "Beaker", educationPath: ["12th PCM (55%+)", "JEE/BITSAT", "B.Tech ChemE (4yr)", "GATE for PSUs"],
        entranceExams: TOP_ENGG_EXAMS, salaryRanges: { entry: "₹4L - ₹8L", mid: "₹8L - ₹18L", senior: "₹18L - ₹35L" }, growthOutlook: "High",
        topColleges: [{ name: "IIT Bombay", location: "Mumbai", fees: "₹2L - ₹8L/yr" }, { name: "ICT Mumbai", location: "Mumbai", fees: "₹1L - ₹2L/yr" }],
        skillsRequired: ["Process Engineering", "Thermodynamics", "Mass/Heat Transfer", "Reaction Engineering", "Aspen/HYSYS", "Process Safety"],
        specializations: ["Petrochemicals", "Pharmaceuticals", "Polymers", "Food Processing", "Environmental Engineering"],
        certifications: ["GATE", "Six Sigma Green Belt", "Process Safety Management", "NEBOSH"],
        topRecruiters: ["Reliance Industries", "ONGC", "Cipla", "ITC", "HUL", "P&G", "Deepak Fertilisers", "BASF"],
        workEnvironment: "Chemical plants, refineries, R&D labs. May involve shift work at manufacturing plants.",
        governmentJobs: ["ONGC", "IOCL", "BPCL", "HPCL", "GAIL", "EIL", "Fertilizer PSUs"],
        privateJobs: ["Pharma Manufacturing", "Petrochemicals", "FMCG", "Specialty Chemicals", "Process Consulting"],
        researchOpportunities: ["CSIR-NCL", "IITs", "ICT Mumbai", "NIPER"],
        entrepreneurshipPotential: "Start specialty chemicals, food processing, or pharma intermediates business",
        futureScope: ["Green hydrogen and sustainable processes", "Biopharma growth", "Circular economy/recycling tech", "Carbon capture"],
        pros: ["Diverse industry options", "PSU jobs available", "Process industries stable", "Global demand for Indian pharma"], cons: ["Plant environment can be hazardous", "Shift work in production", "Location constraints (industrial areas)"],
        category: "Science", timeToComplete: "4 - 6 years" }
    ),
    leafNode("pcm-aerospace", "Aerospace Engineering", "Design aircraft, spacecraft — push the final frontier",
      "Aerospace engineering covers aircraft and spacecraft design, propulsion, aerodynamics, and avionics. With ISRO's Gaganyaan, Chandrayaan missions and private space startups (Skyroot, Agnikul), aerospace is exciting and prestigious. Strong foundation for careers at ISRO, DRDO, and global aviation.",
      "from-indigo-500 to-purple-600",
      { iconName: "Rocket", educationPath: ["12th PCM (60%+)", "JEE Advanced/BITSAT", "B.Tech Aerospace (4yr)", "M.Tech/MS abroad"],
        entranceExams: ["JEE Advanced", "BITSAT", "GATE Aerospace"], salaryRanges: { entry: "₹5L - ₹12L", mid: "₹12L - ₹30L", senior: "₹30L - ₹60L+" }, growthOutlook: "Very High",
        topColleges: [{ name: "IIT Madras", location: "Chennai", fees: "₹2L - ₹8L/yr" }, { name: "IIT Bombay", location: "Mumbai", fees: "₹2L - ₹8L/yr" }, { name: "IIST Thiruvananthapuram", location: "TVM", fees: "₹1L - ₹3L/yr" }],
        skillsRequired: ["Aerodynamics", "Propulsion", "Flight Mechanics", "CAD/FEA/CFD", "MATLAB", "Avionics Basics"],
        specializations: ["Aeronautics (Aircraft)", "Astronautics (Spacecraft)", "Propulsion", "Avionics", "UAV/Drones"],
        certifications: ["GATE Aerospace", "DGCA Certifications", "Private Pilot License (PPL)"],
        topRecruiters: ["ISRO", "DRDO", "HAL", "Airbus", "Boeing", "Bell Helicopter", "Skyroot Aerospace", "Agnikul Cosmos"],
        workEnvironment: "Research labs, manufacturing hangars, design offices. Cutting-edge tech in a highly regulated environment.",
        governmentJobs: ["ISRO", "DRDO", "HAL", "NAL", "ADA", "DGCA"],
        privateJobs: ["Airlines (Engineering)", "Aircraft Manufacturers", "Space Startups", "Drone Industry"],
        researchOpportunities: ["ISRO VSSC/URSC", "DRDO Labs", "NAL", "IIST", "International space research"],
        entrepreneurshipPotential: "Start drone manufacturing company, aerospace component supply, or aviation services",
        futureScope: ["Private space sector booming", "Drone/UAV market $50B+ globally", "Electric aircraft development", "Space tourism emerging"],
        pros: ["Prestigious and exciting", "Cutting-edge technology", "ISRO/DRDO career path", "Global aviation opportunities"], cons: ["Limited seats in top colleges", "Specialized — harder to switch fields", "Regulatory challenges"],
        category: "Science", timeToComplete: "4 - 7 years" }
    ),
    leafNode("pcm-ai-ds", "AI & Data Science Engineering", "Build intelligent systems — extract insights from data",
      "AI/DS is the hottest engineering field. Study machine learning, deep learning, NLP, computer vision, big data, and statistics. With AI transforming every industry, demand for AI engineers is exploding globally. India's AI market projected to reach $17B by 2027.",
      "from-violet-500 to-fuchsia-500",
      { iconName: "Brain", educationPath: ["12th PCM (60%+)", "JEE/BITSAT", "B.Tech AI/DS (4yr)", "M.Tech/MS/Ph.D for research"],
        entranceExams: TOP_ENGG_EXAMS, salaryRanges: { entry: "₹8L - ₹20L", mid: "₹20L - ₹50L", senior: "₹50L - ₹1.5Cr+" }, growthOutlook: "Very High",
        topColleges: TOP_ENGG_COLLEGES,
        skillsRequired: ["Python/R", "Machine Learning", "Deep Learning (TensorFlow/PyTorch)", "Statistics", "Big Data (Spark/Hadoop)", "NLP/CV", "MLOps"],
        specializations: ["NLP", "Computer Vision", "Reinforcement Learning", "MLOps", "Generative AI", "Edge AI"],
        certifications: ["TensorFlow Developer", "AWS ML Specialty", "Google ML Engineer", "NVIDIA DLI"],
        topRecruiters: ["Google", "Microsoft", "Amazon", "OpenAI", "Anthropic", "Flipkart", "Swiggy", "Freshworks", "NVIDIA"],
        workEnvironment: "Modern tech offices, highly remote-friendly. Research-oriented with strong peer collaboration and continuous learning.",
        governmentJobs: ["DRDO AI", "ISRO", "NIC AI", "C-DAC", "NITI Aayog"],
        privateJobs: ["FAANG", "AI Startups", "Product Companies", "Consulting", "Finance AI"],
        researchOpportunities: ["IITs AI Labs", "IISc", "Google Research India", "MSR India", "Wadhwani AI"],
        entrepreneurshipPotential: "Build AI startup — India has 2000+ AI startups, massive VC interest in generative AI",
        futureScope: ["Generative AI is the next platform shift", "AI regulation creating new roles", "Edge AI for IoT devices", "AI in healthcare/drug discovery"],
        pros: ["Highest demand field globally", "Top-tier compensation", "Intellectually stimulating", "Remote-friendly"], cons: ["Very fast-moving field", "High math requirements", "Competition for top roles", "Ethics concerns in AI"],
        category: "Science", timeToComplete: "4 - 7 years" }
    ),
    leafNode("pcm-architecture", "B.Arch (Architecture)", "Design spaces that inspire and function beautifully",
      "B.Arch (5 years) blends art, engineering, and design. Architects design buildings, urban spaces, and interiors. NATA/JEE Main Paper 2 are the entrance exams. With urbanization, smart cities, and real estate growth, architects have growing opportunities in India and globally.",
      "from-rose-400 to-pink-500",
      { iconName: "PenTool", educationPath: ["12th PCM (50%+)", "NATA or JEE Paper 2", "B.Arch (5yr)", "M.Arch (2yr optional)"],
        entranceExams: ["NATA", "JEE Main Paper 2", "CEPT"], salaryRanges: { entry: "₹3L - ₹6L", mid: "₹6L - ₹15L", senior: "₹15L - ₹30L+" }, growthOutlook: "High",
        topColleges: [{ name: "IIT Roorkee", location: "Roorkee", fees: "₹2L - ₹8L/yr" }, { name: "CEPT Ahmedabad", location: "Ahmedabad", fees: "₹3L - ₹10L/yr" }, { name: "SPA Delhi", location: "Delhi", fees: "₹1L - ₹3L/yr" }],
        skillsRequired: ["Design Thinking", "Sketching & Drafting", "AutoCAD/Revit/SketchUp", "3D Modeling (Rhino/Blender)", "Building Codes", "Sustainable Design"],
        specializations: ["Urban Design", "Landscape Architecture", "Interior Design", "Sustainable Architecture", "Heritage Conservation", "Parametric Design"],
        certifications: ["COA Registration", "LEED AP", "GRIHA", "WELL AP"],
        topRecruiters: ["L&T Realty", "Sobha", "DLF", "CP Kukreja Associates", "Hafeez Contractor", "Government PWDs"],
        workEnvironment: "Architecture studios, construction sites, or own practice. Creative and collaborative atmosphere.",
        governmentJobs: ["CPWD", "State PWD", "Urban Development Authorities", "Smart City SPVs", "Heritage Bodies"],
        privateJobs: ["Architecture Firms", "Real Estate Developers", "Interior Design", "Urban Planning"],
        researchOpportunities: ["Urban planning research", "Sustainable design think tanks", "Heritage conservation"],
        entrepreneurshipPotential: "Open your own architecture practice — the classic and most rewarding path",
        futureScope: ["Smart cities creating design demand", "Green building regulations expanding", "VR/AR in architecture design", "Modular construction growth"],
        pros: ["Creative + technical blend", "Own practice potential", "Tangible lasting impact", "Respected profession"], cons: ["Long education (5 years)", "Lower starting pay", "Competitive for top projects", "Client management challenges"],
        category: "Science", timeToComplete: "5 - 7 years" }
    ),
  ],
};

// Additional PCM specializations
export const PCMB_BRANCH: DecisionTreeNode = leafNode(
  "pcmb",
  "PCMB (Physics, Chemistry, Math, Biology)",
  "Keep all doors open — both engineering and medical",
  "PCMB students take all four core science subjects. This keeps both engineering (JEE) and medical (NEET) paths open but is academically intense. Career options include engineering, medicine, biotechnology, bioinformatics, and interdisciplinary fields like biomedical engineering.",
  "from-blue-600 to-purple-500",
  { iconName: "BookOpen", educationPath: ["11th-12th with PCMB", "JEE/NEET/BITSAT", "Engineering or Medical"], entranceExams: [...TOP_ENGG_EXAMS, "NEET-UG"], salaryRanges: ENGG_SALARY, growthOutlook: "Very High",
    specializations: ["Any Engineering branch", "Any Medical degree", "Bioinformatics", "Biomedical Engineering", "Data Science in Healthcare"],
    skillsRequired: ["Multi-disciplinary thinking", "Time Management", "Both Analytical and Biological aptitude", "High Academic Stamina"],
    topColleges: TOP_ENGG_COLLEGES,
    pros: ["All career options open", "Flexibility to switch paths", "Interdisciplinary edge"], cons: ["Very heavy workload", "High stress", "Hard to excel at all subjects", "Limited extracurricular time"],
    category: "Science", timeToComplete: "4-6 years" }
);

export const CS_ELECTIVE: DecisionTreeNode = leafNode(
  "cs-elective",
  "Computer Science Elective (11th-12th)",
  "Dive into coding and computing from school",
  "Some schools offer Computer Science as a core elective in 11th-12th (with PCM). Gives students a head start in programming, data structures, and computational thinking, making college CS courses easier and improving internship/placement prospects.",
  "from-brand-royal to-brand-electric",
  { iconName: "Monitor", educationPath: ["11th-12th with CS elective", "B.Tech CSE/IT (4yr)", "M.Tech/MS (optional)"], entranceExams: TOP_ENGG_EXAMS, salaryRanges: ENGG_SALARY, topColleges: TOP_ENGG_COLLEGES, growthOutlook: "Very High",
    skillsRequired: ["Programming (Python/Java)", "Algorithmic Thinking", "Mathematics", "Web Development Basics", "Database Basics"],
    specializations: ["Software Engineering", "AI & ML", "Cybersecurity", "Game Development", "Data Science"], category: "Science", timeToComplete: "4 - 6 years" }
);

export const ELECTRONICS_ELECTIVE: DecisionTreeNode = leafNode(
  "electronics-elective",
  "Electronics Elective (11th-12th)",
  "Circuits, chips, and communication fundamentals",
  "Some boards offer Electronics as an elective in 11th-12th. Gives hands-on experience with circuits, microcontrollers, and communication basics, providing strong foundation for ECE, Electrical, and related engineering branches.",
  "from-cyan-500 to-blue-500",
  { iconName: "Cpu", educationPath: ["11th-12th with Electronics", "B.Tech ECE/EE (4yr)"], entranceExams: TOP_ENGG_EXAMS, salaryRanges: ENGG_SALARY, topColleges: TOP_ENGG_COLLEGES, growthOutlook: "High",
    skillsRequired: ["Circuit Analysis", "Microcontrollers/Arduino", "Digital Logic", "Physics", "Problem Solving"], category: "Science", timeToComplete: "4 - 6 years" }
);
