import type { DecisionTreeNode } from "../decision-tree.types";
import { leafNode } from "./shared";

// ═══════════════════════════════════════════════
// VOCATIONAL COURSES STREAM
// ═══════════════════════════════════════════════

export const VOCATIONAL_STREAM: DecisionTreeNode = {
  id: "vocational",
  name: "Vocational & Skill-Based Courses",
  shortDescription: "Learn specific job skills directly — from paramedic to beautician",
  detailedDescription: "Vocational courses focus on specific job roles rather than broad academic education. They include paramedical courses (MLT, OTT, Radiology), healthcare (nursing assistant, physiotherapy tech), beauty & wellness, agriculture, travel & tourism, and many more. These courses are typically 1-3 years, job-oriented, and often have 100% placement rates. With India's healthcare, beauty, tourism, and agriculture sectors booming, vocational graduates are in high demand.",
  iconName: "Briefcase",
  color: "from-green-600 to-green-400",
  educationPath: ["10th / 12th Pass", "Vocational course (1-3yr)", "Certification / License", "Direct employment"],
  entranceExams: ["College-specific entrance", "Merit-based admission", "Skill assessment tests", "No centralized exam"],
  topColleges: [
    { name: "State Medical Colleges (Paramedical)", location: "Various", fees: "₹10K - ₹50K/yr" },
    { name: "NSTI (National Skills Training)", location: "Multiple", fees: "₹2K - ₹10K/yr" },
    { name: "PSS Central Institute of Vocational Education", location: "Bhopal", fees: "₹5K - ₹15K/yr" },
  ],
  salaryRanges: { entry: "₹2L - ₹5L", mid: "₹5L - ₹10L", senior: "₹10L - ₹20L" },
  growthOutlook: "High",
  skillsRequired: ["Role-specific Technical Skills", "Communication", "Customer Service", "Practical Aptitude", "Attention to Detail"],
  specializations: ["Paramedical (MLT, OTT, Radiology)", "Healthcare Assistant", "Beauty & Wellness", "Agriculture", "Travel & Tourism", "Event Management"],
  certifications: ["NCVT/SCVT", "Sector Skill Council (SSC) certs", "State Medical Faculty certs", "International certifications (CIDESCO, CIBTAC)"],
  topRecruiters: ["Hospitals & Diagnostic Labs", "Wellness & Salon Chains", "Travel Agencies & Airlines", "Hotels & Resorts", "Agri-Business Companies"],
  workEnvironment: "Extremely varied — hospital lab, beauty salon, airport, farm, event venue. Practical and hands-on rather than desk-based.",
  governmentJobs: ["Government Hospital (Paramedical)", "Railway Hospital", "PSU Wellness Centers", "Agricultural Extension", "Tourism Departments"],
  privateJobs: ["Private Hospitals", "Beauty/Wellness Chains", "Airlines & Hotels", "Agri-Companies", "Event Management"],
  researchOpportunities: ["Limited direct research", "Advanced diplomas → degree → research paths available", "Agriculture vocational → B.Sc Ag → M.Sc → Ph.D"],
  entrepreneurshipPotential: "Start diagnostic lab, beauty salon, travel agency, organic farm, event planning company",
  futureScope: ["Healthcare diagnostics growing at 15-20% CAGR", "Wellness & beauty industry boom", "Medical tourism in India", "Agri-tech and organic farming"],
  pros: ["Job-specific training — high employability", "Short duration (1-3 years)", "Lower education cost", "Direct industry linkage", "Can start own business"],
  cons: ["Lower salary ceiling than degree holders", "Limited academic progression (lateral entry exists)", "Some roles physically demanding", "Perceived lower prestige"],
  category: "Vocational",
  timeToComplete: "1 - 3 years",
  children: [
    leafNode("voc-mlt", "Medical Lab Technology (MLT)", "Run diagnostic tests — the backbone of modern medicine",
      "DMLT (Diploma in Medical Lab Technology) is a 2-year course training students in pathology, microbiology, biochemistry, hematology, and blood bank technology. MLT professionals run the lab tests that doctors rely on for diagnosis. BMLT (3yr degree) available after 12th. Always in demand — no treatment happens without a lab report.",
      "from-teal-500 to-green-600",
      { iconName: "Microscope", educationPath: ["10th / 12th (Science)", "DMLT (2yr) or BMLT (3yr)", "State Medical Faculty Registration", "Hospital / Diagnostic Lab"],
        salaryRanges: { entry: "₹2L - ₹4L", mid: "₹4L - ₹8L", senior: "₹8L - ₹15L" }, growthOutlook: "Very High",
        skillsRequired: ["Sample Collection", "Lab Equipment Operation", "Microbiology", "Biochemistry", "Quality Control"],
        specializations: ["Pathology", "Microbiology", "Biochemistry", "Hematology", "Blood Bank Technology", "Histopathology"],
        topRecruiters: ["Diagnostic Chains (Dr. Lal PathLabs, SRL, Thyrocare)", "Hospitals", "Blood Banks", "Research Labs"],
        workEnvironment: "Hospital laboratory or diagnostic center. Clean, air-conditioned. Involves handling blood/samples (PPE used). Shift-based.",
        governmentJobs: ["Government Hospitals", "AIIMS", "Railway Hospitals", "ESIC Hospitals", "Defence Medical"], privateJobs: ["Diagnostic Lab Chains", "Private Hospitals", "Pharma Research", "Blood Banks"],
        entrepreneurshipPotential: "Start diagnostic collection center or small pathology lab — growing industry, franchise options available",
        futureScope: ["Diagnostic industry growing 15-20% annually", "Home sample collection boom", "Molecular diagnostics (PCR) specialization", "AI-assisted lab diagnostics"],
        pros: ["Always in demand (every patient needs lab)", "Clean, indoor work", "Can start own lab", "Diagnostic chains = organized sector jobs"], cons: ["Shift work (24/7 hospital labs)", "Biohazard exposure (with proper PPE, minimal)", "Repetitive testing", "Standing for long hours"],
        category: "Vocational", timeToComplete: "2 - 3 years" }
    ),
    leafNode("voc-ott", "Operation Theatre Technology (OTT)", "Assist surgeons — be the trusted hand in the OR",
      "Diploma in Operation Theatre Technology (2yr) trains students in sterilization, surgical instrument handling, anesthesia assistance, OT protocols, and emergency preparedness. OT Technologists work closely with surgeons in operating rooms. Every hospital needs them.",
      "from-blue-400 to-cyan-500",
      { iconName: "Stethoscope", educationPath: ["10th / 12th (Science)", "DOTT (2yr) or B.Sc OTT (3yr)", "Registration", "Hospital OR"],
        salaryRanges: { entry: "₹2.5L - ₹5L", mid: "₹5L - ₹10L", senior: "₹10L - ₹18L" }, growthOutlook: "High",
        skillsRequired: ["Sterilization", "Surgical Instrument Knowledge", "Aseptic Techniques", "Emergency Response", "Teamwork (under pressure)"],
        topRecruiters: ["Multi-Specialty Hospitals", "Surgical Centers", "Trauma Centers", "Nursing Homes"],
        workEnvironment: "Operating room — sterile, high-pressure, team environment. Scrubs and full PPE. Adrenaline-filled. No room for error.",
        governmentJobs: ["Government Hospitals", "AIIMS", "Railway Hospitals", "Defence (Military Hospitals)"], privateJobs: ["Private Hospitals", "Surgical Centers", "Nursing Homes"],
        entrepreneurshipPotential: "Start surgical equipment supply business, surgical assistance services, or OT consultancy",
        futureScope: ["Surgical volumes growing (elective + emergency)", "Day-care surgery centers expanding", "Robotic surgery requiring specialized techs"],
        pros: ["Essential in every hospital", "Respected surgical team role", "Adrenaline-filled (not boring)", "Government hospital jobs stable"], cons: ["High-pressure (lives at stake)", "Standing for hours (long surgeries)", "Shift work (emergency surgeries)", "Stressful environment"],
        category: "Vocational", timeToComplete: "2 - 3 years" }
    ),
    leafNode("voc-radiology", "Radiology / X-Ray Technology", "Capture the images that reveal what doctors can't see",
      "Diploma in Radiology/Imaging Technology (2yr) covers X-ray, CT scan, MRI, ultrasound operation, radiation safety, and patient positioning. Radiographers operate imaging equipment in hospitals and diagnostic centers. AI is augmenting (not replacing) this field — skilled operators are still essential.",
      "from-purple-400 to-violet-500",
      { iconName: "Radio", educationPath: ["10th / 12th (Science)", "DRIT (2yr) or B.Sc (3yr)", "AERB certification", "Hospital / Diagnostic Center"],
        salaryRanges: { entry: "₹2.5L - ₹5L", mid: "₹5L - ₹10L", senior: "₹10L - ₹18L" }, growthOutlook: "High",
        skillsRequired: ["Imaging Equipment Operation", "Radiation Safety (ALARA principle)", "Patient Positioning", "Anatomy Knowledge", "Image Processing"],
        specializations: ["CT Scan", "MRI", "Ultrasound", "Interventional Radiology", "Nuclear Medicine"],
        topRecruiters: ["Hospitals", "Diagnostic Imaging Centers", "Teleradiology Companies", "Equipment Companies (Siemens, GE, Philips)"],
        workEnvironment: "Hospital imaging department or diagnostic center. Controlled radiation environment. Mix of patient interaction and technical work.",
        governmentJobs: ["Government Hospitals", "AIIMS", "Railway Hospitals", "Defence Medical"], privateJobs: ["Private Hospitals", "Diagnostic Centers", "Equipment Companies (Applications Specialist)"],
        entrepreneurshipPotential: "Start diagnostic imaging center — MRI/CT centers are capital-intensive but high-revenue",
        futureScope: ["MRI/CT volumes growing", "Teleradiology enabling remote reporting", "AI in imaging (assistant, not replacement)", "PET-CT for cancer diagnostics"],
        pros: ["Respected hospital role", "Clean, tech-driven environment", "Specialization (MRI) pays more", "No night shifts in diagnostic centers"], cons: ["Radiation exposure (minimized with protocols)", "Night shifts in hospital ER", "Standing for long periods", "MRI is claustrophobic environment"],
        category: "Vocational", timeToComplete: "2 - 3 years" }
    ),
    leafNode("voc-beauty", "Beauty & Wellness", "Transform appearances — build confidence through beauty care",
      "The beauty & wellness industry in India is a ₹1 lakh crore+ market growing at 18% CAGR. Diploma courses (1-2yr) cover skin care, hair styling, makeup artistry, nail art, spa therapy, and salon management. Career paths: salon professional → senior stylist → salon manager → own business. International certifications (CIDESCO, CIBTAC) enable global careers.",
      "from-pink-300 to-rose-400",
      { iconName: "Sparkles", educationPath: ["10th Pass", "Diploma in Beauty/Wellness (1-2yr)", "Advanced certifications", "Salon / Cruise / Own business"],
        salaryRanges: { entry: "₹1.5L - ₹3.5L", mid: "₹3.5L - ₹8L", senior: "₹8L - ₹20L+" }, growthOutlook: "Very High",
        skillsRequired: ["Skin/Hair Care Techniques", "Makeup Artistry", "Customer Service", "Product Knowledge", "Hygiene & Safety"],
        specializations: ["Hair Styling", "Makeup Artistry", "Bridal Makeup", "Skin Care / Aesthetics", "Spa Therapy", "Nail Art", "Barbering"],
        certifications: ["NSDC Beauty & Wellness", "CIDESCO (International)", "CIBTAC (UK)", "City & Guilds", "Brand certifications (L'Oréal, MAC)"],
        topRecruiters: ["Lakmé Salon", "Naturals", "Juice Salon", "Enrich", "YLG", "Cruise Lines", "5-Star Hotel Spas"],
        workEnvironment: "Salon, spa, cruise ship, or freelance (bridal/home service). Clean, well-lit, social environment. Weekends may be busiest.",
        governmentJobs: ["ITDC Hotel Spas", "Government Wellness Centers"], privateJobs: ["Salon Chains", "Hotel Spas", "Cruise Lines", "Bridal/Freelance"],
        entrepreneurshipPotential: "Start own salon or freelance bridal makeup business — one of the most successful self-employment categories in India",
        futureScope: ["Beauty industry growing 18% CAGR", "Men's grooming segment exploding", "Cruise/hotel spa demand", "Medical aesthetics (cosmetology) emerging"],
        pros: ["Creative and social career", "Huge industry growth", "Self-employment very viable", "International certifications = global career", "Bridal can earn ₹20K-₹1L+ per event"], cons: ["Starting pay is low", "Weekend/holiday work", "Standing for long hours", "Client satisfaction pressure (weddings!)"],
        category: "Vocational", timeToComplete: "1 - 2 years" }
    ),
    leafNode("voc-agriculture", "Agriculture & Allied Vocational", "Feed the nation — modern, tech-driven farming",
      "Vocational agriculture courses (1-2yr) cover modern farming techniques, organic farming, greenhouse/polyhouse, soil science, seed technology, dairy farming, poultry, fisheries, and agri-business. With India being an agricultural powerhouse and agri-tech booming, skilled agri-professionals are in demand.",
      "from-lime-500 to-green-700",
      { iconName: "Sprout", educationPath: ["10th Pass", "Vocational Agri course (1-2yr)", "Practical training", "Job / Own farm / B.Sc Ag lateral"],
        salaryRanges: { entry: "₹2L - ₹4L", mid: "₹4L - ₹8L", senior: "₹8L - ₹18L" }, growthOutlook: "High",
        skillsRequired: ["Crop/Animal Knowledge", "Soil Science Basics", "Modern Techniques", "Business Sense", "Physical Stamina"],
        specializations: ["Organic Farming", "Greenhouse/Polyhouse", "Dairy Farming", "Poultry", "Fisheries", "Agri-Business", "Horticulture"],
        topRecruiters: ["Agri-Companies (ITC, Godrej Agrovet)", "Dairy Cooperatives (Amul)", "Seed Companies", "Agri-Tech Startups", "NGOs"],
        workEnvironment: "Farm, greenhouse, dairy, or fishery. Outdoor or semi-outdoor. Hands-on with plants/animals. Agri-tech roles may be office-based.",
        governmentJobs: ["Agriculture Extension Officer", "State Agriculture Depts", "NABARD", "Krishi Vigyan Kendras (KVK)", "FCI"], privateJobs: ["Agri-Business Companies", "Dairy/Poultry Industry", "Seed Companies", "Agri-Tech Startups"],
        entrepreneurshipPotential: "Start organic farm, dairy/poultry unit, polyhouse, mushroom cultivation, or agri-input supply business",
        futureScope: ["Agri-tech startups booming", "Organic/natural farming premium market", "Food processing industry growth", "Government doubling farmer income focus", "Contract farming"],
        pros: ["India = agriculture country (always relevant)", "Agri-tech is modernizing the field", "Government schemes and subsidies available", "Self-employment directly in farming"], cons: ["Weather-dependent (climate risks)", "Physically demanding", "Rural/remote locations", "Market price volatility", "Lower initial income"],
        category: "Vocational", timeToComplete: "1 - 2 years" }
    ),
    leafNode("voc-tourism", "Travel & Tourism", "Show the world to people — India's sunrise industry",
      "Diploma in Travel & Tourism (1-2yr) covers travel operations, tour planning, ticketing (GDS — Amadeus/Galileo), hospitality, destination knowledge, and customer handling. India's tourism sector is booming with domestic and international travel. Careers span travel agencies, airlines, hotels, cruise lines, and tour operations. IATA certification is globally recognized.",
      "from-blue-400 to-sky-600",
      { iconName: "Plane", educationPath: ["10th / 12th Pass", "Diploma in Travel/Tourism (1-2yr)", "IATA certification", "Travel Agency / Airline / Hotel"],
        salaryRanges: { entry: "₹2L - ₹4L", mid: "₹4L - ₹10L", senior: "₹10L - ₹20L" }, growthOutlook: "Very High",
        skillsRequired: ["Travel Operations", "GDS (Amadeus)", "Customer Service", "Destination Knowledge", "Sales & Communication"],
        certifications: ["IATA/UFTAA", "Galileo/Amadeus GDS", "Tour Guide License", "Scuba/PADI (adventure tourism)"],
        topRecruiters: ["MakeMyTrip", "Thomas Cook", "Cox & Kings", "Airlines (IndiGo, Air India, Emirates)", "Hotels & Resorts", "OTA Platforms"],
        workEnvironment: "Travel agency office, airport, hotel, or tour operations. Involves travel perks (fam trips, discounted tickets). Customer-facing.",
        governmentJobs: ["ITDC", "State Tourism Corporations", "IRCTC", "Airport Authority", "Government Tourist Offices"], privateJobs: ["Travel Agencies", "OTA Companies", "Airlines", "Hotels/Resorts", "Cruise Lines", "MICE (Event Travel)"],
        entrepreneurshipPotential: "Start travel agency, tour operation company, homestay/boutique resort, or adventure tourism company",
        futureScope: ["India tourism booming (domestic + international)", "Medical tourism hub", "Adventure tourism emerging", "Spiritual/wellness tourism", "Weekend travel culture growing"],
        pros: ["Travel perks (discounts/fam trips)", "Growing industry", "Self-employment friendly", "Fun, people-oriented work", "Global career options (cruise, airlines)"], cons: ["Peak season work pressure", "Commission-based earnings in sales", "Dealing with travel disruptions (unhappy customers)", "Online booking competing with agencies"],
        category: "Vocational", timeToComplete: "1 - 2 years" }
    ),
    leafNode("voc-event", "Event Management", "Create unforgettable experiences — from weddings to conferences",
      "Event management is India's fastest-growing creative career. Diploma (1yr) covers event planning, budgeting, vendor management, décor, AV/technical, logistics, and client handling. Career progression: assistant → coordinator → manager → own event company. India's wedding industry alone is $50B+. Plus corporate events, concerts, exhibitions, and sports events.",
      "from-fuchsia-400 to-purple-600",
      { iconName: "PartyPopper", educationPath: ["10th / 12th Pass", "Diploma in Event Mgmt (1yr)", "Internship with event company", "Manager → Own company"],
        salaryRanges: { entry: "₹2L - ₹4L", mid: "₹4L - ₹10L", senior: "₹10L - ₹25L+" }, growthOutlook: "Very High",
        skillsRequired: ["Planning & Organization", "Vendor Management", "Budgeting", "Creativity", "Crisis Management", "Negotiation"],
        specializations: ["Wedding Planning", "Corporate Events", "Exhibitions/Trade Shows", "Concerts/Festivals", "Sports Events", "Virtual/Hybrid Events"],
        topRecruiters: ["Wizcraft", "Encompass", "Wedding Sutra", "70 EMG", "Percept", "5-Star Hotels (Banquet)", "Corporate Event Depts"],
        workEnvironment: "Office for planning, event venues (hotels, convention centers, outdoor) for execution. High-energy, creative. Long hours during events but rewarding.",
        governmentJobs: ["ITDC", "State Tourism Event Depts", "Municipal Event Coordination"], privateJobs: ["Event Management Companies", "Hotels (Banquet/Events)", "Corporate (Event Marketing)", "Wedding Planning Companies"],
        entrepreneurshipPotential: "Start wedding planning company, corporate event agency, or niche event business (baby showers, themed parties)",
        futureScope: ["Indian wedding industry = $50B+", "Corporate India spending on events", "Sports leagues (IPL, ISL) creating event jobs", "Music festivals & concert boom", "Virtual/hybrid events as new format"],
        pros: ["Creative, high-energy career", "Wedding industry is recession-proof", "Start own company with low capital", "Every event is different (no boredom)"], cons: ["High-pressure deadlines", "Long, irregular hours (weekends/evenings)", "Stressful when things go wrong", "Seasonal (nov-feb peak for weddings)"],
        category: "Vocational", timeToComplete: "1 year" }
    ),
    leafNode("voc-animation", "Animation & Multimedia", "Bring stories to life through art and technology",
      "Diploma/Certificate courses (6mo-2yr) in animation, VFX, motion graphics, 3D modeling, video editing, and game design. India's AVGC (Animation, VFX, Gaming, Comics) sector is growing at 16% CAGR. Opportunities in film/TV/OTT VFX, game development, advertising, and e-learning content.",
      "from-indigo-500 to-violet-500",
      { iconName: "Clapperboard", educationPath: ["10th / 12th Pass", "Diploma/Cert in Animation (6mo-2yr)", "Portfolio building", "Studio / Freelance"],
        salaryRanges: { entry: "₹2L - ₹5L", mid: "₹5L - ₹12L", senior: "₹12L - ₹30L+" }, growthOutlook: "Very High",
        skillsRequired: ["3D Modeling (Maya/Blender)", "Animation Principles", "Visual Storytelling", "Software Proficiency", "Creativity"],
        specializations: ["3D Animation", "VFX Compositing", "Motion Graphics", "Game Design", "Video Editing", "Character Animation"],
        topRecruiters: ["MPC", "DNEG", "Technicolor", "Red Chillies VFX", "Prime Focus", "Byju's (animation)", "Gaming Studios (Ubisoft, Zynga)"],
        workEnvironment: "Studio office. Desk-based, creative. Rendering-heavy. OTT boom has created massive VFX demand. Freelance/remote possible.",
        governmentJobs: ["Film Division", "DD", "State Film Corporations"], privateJobs: ["VFX Studios", "Gaming Companies", "OTT/Content Studios", "Advertising Agencies", "EdTech (Animated Content)"],
        entrepreneurshipPotential: "Start animation/ VFX studio, YouTube animation channel, freelance motion graphics business, or game dev studio",
        futureScope: ["OTT content explosion = more VFX work", "Gaming industry in India growing 5x by 2030", "AR/VR/metaverse content emerging", "AI-assisted animation tools accelerating production"],
        pros: ["Creative + technical (perfect combo)", "OTT/VFX boom = jobs", "Global remote work possible", "Portfolio-based — degree not critical"], cons: ["Long rendering hours (deadline crunch)", "Competitive entry-level", "Software licensing costs (if freelance)", "Sitting for long hours (health impact)"],
        category: "Vocational", timeToComplete: "6 months - 2 years" }
    ),
  ],
};
